export const topicYearTabs = ['2025', '2024', '2023']
export const topicSphereList = [
  { key: 'livelihood', label: '民生', size: 'sm', num: 229 },
  { key: 'four', label: '四个发力', size: 'xl', num: 236 },
  { key: 'law', label: '法治四川', size: 'md', num: 75 },
  { key: 'plan', label: '发展规划', size: 'md', num: 82 },
  { key: 'safety', label: '安全发展', size: 'sm', num: 6 },
  { key: 'traffic', label: '交通', size: 'lg', num: 57 },
  { key: 'chengyu', label: '成渝地区双城经济圈', size: 'wide', num: 61 },
  { key: 'finance', label: '财税金融', size: 'lg', num: 38 },
  { key: 'ecology', label: '生态', size: 'lg', num: 8 },
  { key: 'culture', label: '文化旅游', size: 'xl', num: 52 },
  { key: 'industry', label: '新质生产力', size: 'md', num: 6 },
  { key: 'reform', label: '改革开放', size: 'lg', num: 41 },
  { key: 'grain', label: '天府粮仓', size: 'sm', num: 25 },
  { key: 'integration', label: '城乡融合', size: 'md', num: 5 },
  { key: 'other', label: '其他', size: 'sm', num: 55 },
]
export const topicListByYear = {
  2025: [
    {
      id: '25-liv-01',
      title: '关于学前教育教师享受中小学教师同等待遇的建议',
      author: '王永兰',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-02',
      title: '关于适当放宽幼升小年龄范围的建议',
      author: '魏琴',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-03',
      title: '关于加强普通高中职业生涯规划教育的建议',
      author: '欧阳梅',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-04',
      title: '关于“双一流”扩容增设区域急需赛道的建议',
      author: '尚丽平',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-05',
      title: '关于加强国产工业软件人才培养的建议',
      author: '张祖涛',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-06',
      title: '关于进一步推进地方高水平应用型高校建设的建议',
      author: '张祖涛',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-07',
      title: '关于进一步提高全日制博士研究生奖助学金的建议',
      author: '张祖涛',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-08',
      title: '关于普及人工智能教育培养拔尖创新人才的建议',
      author: '苟兴龙',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-09',
      title: '关于将落下闳的科研精神和贡献编入全国统编教材的建议',
      author: '李君',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-10',
      title: '关于在青少年学生群体中加强人民代表大会制度教育的建议',
      author: '罗春梅',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-11',
      title: '关于在青少年学生群体中加强人民代表大会制度教育的建议',
      author: '罗春梅',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-12',
      title: '关于加强新时代伟大变革成功案例和红色文化资源融入思想政治教育的建议',
      author: '苟兴龙',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-13',
      title: '关于将革命老区省属应用型本科高校纳入国家支持计划的建议',
      author: '苟兴龙',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-14',
      title: '关于扩大国家银龄教师行动计划实施范围和规模的建议',
      author: '苟兴龙',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-15',
      title: '关于加强国家实验室战略人才力量及其后备队伍建设的建议',
      author: '吴忠跃',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-16',
      title: '改革我国高校专利激励政策 切实规避投机行为提高质量与转化率',
      author: '里赞',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-17',
      title: '优化我国高校科研人员出境持用证件政策 切实促进对外学术交流合作',
      author: '里赞',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-18',
      title: '关于进一步加强民生建设筑牢普惠性基础性兜底性保障的建议',
      author: '吉列子日',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-19',
      title: '关于积极应对农村人口老龄化 加快完善我国农村养老服务体系建设',
      author: '里赞',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-20',
      title: '关于加快建立我国公共监护人制度的建议',
      author: '里赞',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-21',
      title: '关于支持革命老区提升就业公共服务水平的建议',
      author: '胡晓玲',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-22',
      title: '关于加大对革命老区就业创业补助资金转移支付力度的建议',
      author: '李君',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-23',
      title: '关于坚决纠正就业领域年龄歧视的建议',
      author: '郑功成',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-24',
      title: '关于大学生不愿意就业与缓就业的调研及相关的建议',
      author: '张祖涛',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-25',
      title: '关于高度重视解决国有企业、事业单位社会招聘中学校、学历歧视的建议',
      author: '刘廷安',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-26',
      title: '关于消除就业和晋升领域第一学历歧视的建议',
      author: '',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-27',
      title: '关于优化我国无障碍设施建设与管理的建议',
      author: '钟波',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-28',
      title: '关于支持建筑业高质量发展的建议',
      author: '郑望春',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-29',
      title: '关于加快建立住宅保险制度的建议',
      author: '郑功成',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-30',
      title: '关于加快促进农村地区医养结合发展的建议',
      author: '杨兴平',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-31',
      title: '关于强化食品安全监管体系建设筑牢“从农田到餐桌”全链条防线的建议',
      author: '吉列子日',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-32',
      title: '关于支持欠发达地区拓展城镇开发空间的建议（延伸）',
      author: '',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-33',
      title: '关于优化国土空间规模使用要求的建议',
      author: '苟兴龙',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-34',
      title: '关于聚焦家庭医生和社区养老，让家庭医生真正走进千家万户的建议',
      author: '甘华田',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-eco-01',
      title: '关于优化空气质量考评体系实现环境经济和社会效益共赢的建议',
      author: '尚丽平',
      link: '',
      topicKey: 'ecology',
    },
    {
      id: '25-eco-02',
      title: '关于进一步加强山洪地质灾害避险搬迁政策支持的建议',
      author: '彭映梅',
      link: '',
      topicKey: 'ecology',
    },
    {
      id: '25-eco-03',
      title: '关于加强野生动物致害补偿工作的建议',
      author: '余绍容',
      link: '',
      topicKey: 'ecology',
    },
    {
      id: '25-eco-04',
      title: '关于有效保护好野生动物，避免对农民群众生产生活造成严重影响的建议',
      author: '郑望春',
      link: '',
      topicKey: 'ecology',
    },
    {
      id: '25-eco-05',
      title: '关于加强西部山区生态环境宣传保护推动全民协同参与生态环境保护的建议',
      author: '郑望春',
      link: '',
      topicKey: 'ecology',
    },
    {
      id: '25-eco-06',
      title: '关于调整矿山地质环境保护与土地复垦方案编制审批流程的建议',
      author: '郑望春',
      link: '',
      topicKey: 'ecology',
    },
    {
      id: '25-eco-07',
      title: '关于加强野生动物危害防控和致害补偿的建议',
      author: '',
      link: '',
      topicKey: 'ecology',
    },
    {
      id: '25-eco-08',
      title: '关于有效保护好野生动物 避免对农民群众生产生活造成严重影响的建议',
      author: '',
      link: '',
      topicKey: 'ecology',
    },
    {
      id: '25-cul-01',
      title: '关于大力传承弘扬三苏文化东坡文化深化家庭家教家风建设的建议',
      author: '黄河',
      link: '',
      topicKey: 'culture',
    },
    {
      id: '25-cul-02',
      title: '关于支持达州市联动周边打造大巴山国际旅游度假区的建议',
      author: '胡晓玲',
      link: '',
      topicKey: 'culture',
    },
    {
      id: '25-cul-03',
      title: '关于支持九寨沟景区湖群沼泽化治理的建议',
      author: '王树明',
      link: '',
      topicKey: 'culture',
    },
    {
      id: '25-cul-04',
      title: '关于推进大熊猫入住“蜀南竹海”的建议',
      author: '魏琴',
      link: '',
      topicKey: 'culture',
    },
    {
      id: '25-cul-05',
      title: '关于大力推进文化产品出海的建议',
      author: '杨兴平',
      link: '',
      topicKey: 'culture',
    },
    {
      id: '25-ind-01',
      title: '关于加强科技赋能、将薯业纳入国家农业新质生产力战略布局的建议',
      author: '魏彦玉',
      link: '',
      topicKey: 'industry',
    },
    {
      id: '25-ind-02',
      title: '关于在四川打造“光经济”新质生产力战略高地的建议',
      author: '罗先刚',
      link: '',
      topicKey: 'industry',
    },
  ],
  2024: [
    {
      id: '24-four-001',
      title: '关于支持在四川宜宾建立国家全固态电池创新中心的建议',
      author: '廖文彬',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-002',
      title: '关于支持四川先行先试在重点领域进行紧缺人才自主培养机制创新的建议',
      author: '罗先刚',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-003',
      title: '关于支持在川布局建设综合类、中医类国家医学中心的建议',
      author: '全团',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-004',
      title: '关于支持四川建设国家工业云制造创新中心的建议',
      author: '全团',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-005',
      title:
        '关于加快推进钒钛资源综合开发利用科技攻关和钒钛资源综合利用国家重点实验室优化重组的建议',
      author: '全团',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-006',
      title: '关于在专利法中增加国家使用权的建议',
      author: '尚丽平',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-007',
      title: '关于发挥国企产业链链长作用，培植核心领域产业联盟，打造中国式技术标准和输出能力的建议',
      author: '李慧',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-008',
      title: '建立有关国家实验室法律配套基础制度的建议',
      author: '吴忠跃',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-009',
      title: '关于国家实验室硕博士授予权的建议',
      author: '吴忠跃',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-010',
      title: '关于设立国家西部人才基金的建议',
      author: '尧德中',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-011',
      title: '关于支持钒钛资源综合利用国家重点实验室优化重组的建议',
      author: '邹明',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-012',
      title: '关于支持构建西部矿产品（钒钛钢铁）骨干流通走廊的建议',
      author: '邹明',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-014',
      title: '关于尽快建立动物新品种权保护体系的建议',
      author: '杨武云',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-015',
      title: '关于严厉打击知识产权恶意诉讼 规范权利行使的建议',
      author: '钟波',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-016',
      title: '关于推进农村地区网络覆盖的建议',
      author: '郑望春',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-017',
      title: '关于支持中小型燃气轮机现代产业链建设的建议',
      author: '曹天兰',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-018',
      title: '关于加快制造业“智改数转”，高质量建设成渝地区高端装备产业集群的建议',
      author: '曹天兰',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-019',
      title: '关于支持四川晶硅光伏产业发展的建议案',
      author: '陈光浩',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-020',
      title: '关于支持四川建设航空航天装备先进制造业集群的建议',
      author: '陈张铭',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-021',
      title: '关于支持自贡建设氢能装备制造和应用基地的建议',
      author: '陈张铭',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-022',
      title: '关于支持四川创建国家新型工业化示范区加快打造国家战略腹地的建议',
      author: '翟刚',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-023',
      title: '关于支持四川省建设全球稀土资源综合利用基地的建议',
      author: '翟刚',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-024',
      title: '关于支持达州建设热电联产循环经济园的建议',
      author: '苟兴龙',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-025',
      title: '关于依托标志性产品链主企业，在宜宾建设全国近零碳园区的建议',
      author: '廖文彬',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-026',
      title: '关于进一步加快我国多种储能建设推进低碳中国进程的建议',
      author: '刘汉元',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-027',
      title: '关于加快工业互联网平台产业发展的建议',
      author: '柳江',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-028',
      title: '关于大力推进县域工业数字化转型，助力打造新质生产力的建议',
      author: '马奎',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-029',
      title: '关于支持雅安开展算力电力协同试点的建议',
      author: '彭映梅',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-030',
      title: '关于支持四川探索试点碳足迹管理先行先试建设动力电池产业绿色零碳示范区的建议',
      author: '全团',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-031',
      title: '关于支持成都纳入国家数据基础设施区域性节点布局的建议',
      author: '全团',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-032',
      title: '支持四川省自贡市创建国家新型工业化示范区',
      author: '李慧',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-033',
      title: '关于“加强丝纺行业科研 助力行业数字化转型”的建议',
      author: '王丽',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-034',
      title: '关于落实绿电交易政策进一步支持水电清洁能源纳入绿电范围的建议',
      author: '庹庆明',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-035',
      title: '关于加快四川民族地区交通建设和清洁能源开发的建议',
      author: '何延政',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-036',
      title: '关于建立电网碳排放因子数据库 完善绿色电力交易机制的建议',
      author: '刘汉元',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-037',
      title: '关于支持清洁能源开发和电力通道建设的建议',
      author: '罗振华',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-038',
      title: '关于进一步健全完善氢能管理制度体系的建议',
      author: '吴群刚',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-039',
      title: '关于在川布局建设国家清洁能源',
      author: '吴群刚',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-040',
      title: '关于支持西部清洁能源省份加强钒钛、晶硅光伏等绿色载能产业发展的建议',
      author: '邹明',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-041',
      title: '关于推动低空经济加快发展的建议',
      author: '陈张铭',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-042',
      title: '关于健全无人机安全管理法律体系 促进低空经济安全有序发展的建议',
      author: '刘传健',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-043',
      title: '关于大力发展低空经济加快构建新应用场景的建议',
      author: '曾洪扬',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-044',
      title: '关于支持在四川打造商业航天产业基地的建议',
      author: '翟刚',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-045',
      title: '关于促进大模型产业生态链建设，推进产业化应用落地的建议',
      author: '柳江',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-046',
      title: '关于促进家庭服务机器人产业应用落地的建议',
      author: '柳江',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-047',
      title: '关于紧抓“AI+算力”机遇，加大对西南地区智算产业发展支持的建议',
      author: '马奎',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-048',
      title: '围绕人工智能为代表的新质生产力发展强基固本建议',
      author: '唐安斌',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-049',
      title: '关于在四川布局建设航空领域高能级创新平台和国家战略性新兴产业集群的建议',
      author: '韩晓军',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-050',
      title: '关于支持在四川打造大飞机综合性产业备份基地的建议',
      author: '韩晓军',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-051',
      title: '关于将成都航空枢纽定位为全方位门户复合型国际航空枢纽的建议',
      author: '黄强',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-052',
      title: '关于加快创新型人才培养 提升中国民航国际竞争力的建议',
      author: '刘传健',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-053',
      title: '关于加快修订出台《中华人民共和国民用航空法》的建议',
      author: '刘传建',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-054',
      title: '关于加强中医药行业知识产权保护的几点建议',
      author: '耿福能',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-055',
      title: '关于中医药走出海外 国际化发展的建议',
      author: '耿福能',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-056',
      title: '关于以野生珍贵、濒危动物为来源的中药管理建议',
      author: '耿福能',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-057',
      title: '关于办理涉及以野生珍贵、濒危动物为来源的中药案件的建议',
      author: '耿福能',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-058',
      title: '关于中医数字化推进健康网格化服务全民体系建设的建议',
      author: '耿福能',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-059',
      title: '关于支持全国革命老区重点城市巴中中医药产业高质量发展的建议',
      author: '高鹏凌',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-060',
      title: '关于加快推进将天冬纳入食药物质目录管理的建议',
      author: '张永',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-061',
      title: '关于规范网络经济、鼓励支持实体经济，发展新质生产力的建议',
      author: '耿福能',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-062',
      title: '关于集聚创新和资源要素推动地方国企发展新质生产力的建议',
      author: '王诚',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-063',
      title: '关于整治“网红”乱象构建和谐网络经济生态的建议',
      author: '耿福能',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-064',
      title: '关于加强网络治理的建议',
      author: '李君',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-065',
      title:
        '关于规范和限制电商行业，防止其野蛮生长，消灭就业岗位，促进社会稳定、国家安全和经济健康发展的建议',
      author: '李玉梅',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-066',
      title: '关于营造健康网络空间的建议',
      author: '唐成凤',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-067',
      title: '关于规范美团、大众点评等平台费用收取及加强食品安全监管的建议',
      author: '王丽',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-068',
      title: '关于进一步保障维护网络安全的建议',
      author: '王麒',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-069',
      title: '关于加强数字乡村建设的建议',
      author: '余绍容',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-070',
      title: '关于积极推进数字化技术应用于民生保障事业的建议',
      author: '郑功成',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-071',
      title: '关于打造我国西南地区CCUS产业中心的建议',
      author: '文绍牧',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-072',
      title: '关于高质量开展四川盆地千亿立方米天然气生产基地建设的建议',
      author: '文绍牧',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-073',
      title: '关于加大页岩油气资源勘探开发和增储上产力度的建议',
      author: '文绍牧',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-074',
      title: '关于加快完善我国能源应急保障体系建设的建议',
      author: '文绍牧',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-075',
      title: '关于完善《矿产资源法》保障国家油气能源安全的建议',
      author: '文绍牧',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-076',
      title: '关于实施页岩气资源地优惠政策的建议（联合建议）',
      author: '余先河',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-077',
      title: '关于支持渠县现代粮油园区创建国家级现代农业产业园区的建议',
      author: '胡晓玲',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-078',
      title: '关于调整山区农业发展保障结构，确保传统优势产业可持续发展的建议',
      author: '胡晓玲',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-079',
      title: '关于支持四川省凉山彝族自治州创建国家马铃薯产业集群的建议',
      author: '吉列子日',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-080',
      title: '关于协同推动粮经烟融合发展的建议',
      author: '李君',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-081',
      title: '关于规范家禽屠宰行业准入标准 助力行业有序健康发展的建议',
      author: '刘汉元',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-082',
      title: '关于推动明月山绿色发展示范带竹产业高质量发展的建议',
      author: '吕祖艳',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-083',
      title: '关于支持川东北地区发展农产品精深加工的建议',
      author: '欧阳梅',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-084',
      title: '关于加强适合中高山区农机设备研发和推广的建议',
      author: '彭映梅',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-085',
      title: '关于支持米易县国家现代农业产业园创建的建议',
      author: '王永兰',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-086',
      title: '关于加快启动建立区域农业新质生产力集中示范片的建议',
      author: '吴德',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-087',
      title: '关于在川布局建设国家农业高新技术',
      author: '吴群刚',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-088',
      title: '关于持续加大对国家农高区创建工作支持力度的建议',
      author: '余绍容',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-089',
      title: '关于持续加强少数民族地区、欠发达地区基础设施建设让农民共同富裕乡村全面振兴发展的建议',
      author: '郑望春',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-090',
      title: '关于持续加强“宜居、宜业和美乡村”建设”需求的建议',
      author: '郑望春',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-091',
      title: '关于以科技创新为引擎培育“三农”新质生产力，全面推进乡村振兴的建议',
      author: '耿福能',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-092',
      title: '关于设立乡村污水处理专项资金的建议',
      author: '曾娜',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-093',
      title: '关于加大对通川区建设“国家乡村振兴示范县”支持力度的建议',
      author: '胡晓玲',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-094',
      title: '关于交通建设支持政策多向乡村振兴重点帮扶地区倾斜的建议',
      author: '吉列子日',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-095',
      title: '关于加大扶持农村集体经济发展的建议',
      author: '李君',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-096',
      title: '关于加大农村生活垃圾处理力度的建议',
      author: '李君',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-097',
      title: '关于保障农村建设用地和设施用地的建议',
      author: '李君',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-098',
      title: '关于城乡融合以工引农以农助农促发展的建议',
      author: '李树林',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-099',
      title: '关于做大做强“强村公司”推进乡村全面振兴的建议',
      author: '杨心平',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-100',
      title: '关于持续支持大熊猫国家公园建设的建议',
      author: '庹庆明',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-101',
      title: '关于加快将世界自然遗产保护整合到国家公园并勘界立标的建议',
      author: '庹庆明',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-102',
      title: '关于进一步加强凉山山系大熊猫保护的建议',
      author: '侯蓉',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-103',
      title: '关于支持四川省雅安市宝兴县纳入国家生态综合补偿试点县的建议',
      author: '庹庆明',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-104',
      title: '关于在美丽城市建设中给予四川省广元市倾斜支持的建议',
      author: '董里',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-105',
      title: '关于减少燃放烟花爆竹带来大气污染的建议',
      author: '董伟',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-106',
      title: '关于推动城镇污水治理两年攻坚行动的建议',
      author: '苟兴龙',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-107',
      title: '关于全面推行生态系统生产总值（GEP）核算并建立发布机制的建议',
      author: '梁伟',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-108',
      title: '关于加快推动医疗机构污水新污染物治理能力提升的建议',
      author: '刘政',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-109',
      title: '关于进一步推动可再生能源健康可持续发展的建议',
      author: '朱永繁',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-110',
      title: '关于支持四川省打造美丽中国先行区的建议',
      author: '全团',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-111',
      title: '关于简化我国氦气回收利用程序的建议',
      author: '李慧',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-112',
      title: '关于支持万源生态功能区产业准入负面清单优化调整的建议',
      author: '文绍牧',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-113',
      title: '关于支持四川大渡河丹巴水电站环评送审工作建议',
      author: '余德春',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-114',
      title: '关于明确长江保护有关条款适用范围和对化工项目认定标准进行解释的建议',
      author: '全团',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-115',
      title: '关于有效保护好野生动物不造成农民群众生产生活严重影响的建议',
      author: '郑望春',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-116',
      title: '关于支持全国革命老区重点城市巴中实施山水林田湖草一体化保护和修复项目的建议',
      author: '戴学斌',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-117',
      title: '关于将每年7月25日设立为古树名木保护日的建议',
      author: '刘素英',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-118',
      title: '关于支持达州建设多维空间复合林业经济示范带的建议',
      author: '胡晓玲',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-119',
      title: '关于加大生物多样性保护支持力度的建议',
      author: '江吉村',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-120',
      title: '关于支持若尔盖国家公园创建的建议',
      author: '罗振华',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-121',
      title: '关于完善林草碳汇项目开发机制的建议',
      author: '彭映梅',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-122',
      title: '关于支持四川贡嘎山山水林田湖草沙冰一体化保护和修复工程的建议',
      author: '余德春',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-123',
      title: '关于加快推动大科学装置成果转化发挥大科学装置原始策源作用的建议',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-124',
      title: '关于推动高质量人工智能发展，提升国际软实力的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-125',
      title: '关于新型举国科研体系推动生物医药卡脖子技术发展的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-126',
      title: '关于建设国家元宇宙创新应用先导区的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-127',
      title: '关于国家智能网联汽车“车路云一体化”应用试点的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-128',
      title: '关于国家数据基础设施区域性节点布局的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-129',
      title: '关于推动高质量人工智能发展，提升国际软实力的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-130',
      title: '关于利用数字技术为畜牧业节粮提效注入新质生产力的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-131',
      title: '关于树牢大食物观建好森林粮库的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-132',
      title: '关于推动“科技-农业-金融”良性循环助力乡村振兴和“农业强国”建设的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-133',
      title: '关于多措并举推动生猪行业高质量发展的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-134',
      title: '关于强化乡村人才培养激发乡村振兴活力的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-135',
      title: '“万企兴万村”行动暨托底性帮扶',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-136',
      title: '关于打造美丽中国先行区的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    { id: '24-four-137', title: '新质生产力+生态环保', author: '', link: '', topicKey: 'four' },
    {
      id: '24-law-001',
      title: '关于最高人民法院加大力度推进裁判文书上网的建议',
      author: '庹庆明',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-002',
      title: '关于对刑法第215条司法解释的建议',
      author: '曾娜',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-003',
      title: '关于进一步深化执行管理体制改革，强化执行联动的建议',
      author: '李世亮',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-004',
      title: '关于进一步规范法律服务市场管理的建议',
      author: '李世亮',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-005',
      title: '关于加大对证券违法犯罪活动的刑事惩戒力度的建议',
      author: '李世亮',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-006',
      title: '关于加强涉外法治体系高质量建设的建议',
      author: '李世亮',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-007',
      title: '关于在死刑复核阶段向辩护律师提供电子卷宗的建议',
      author: '李世亮',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-008',
      title: '关于修改《刑法》第31条的建议',
      author: '李世亮',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-009',
      title: '关于构建全国统一且适合我国国情发展的预重整制度的建议',
      author: '李世亮',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-011',
      title: '关于将《残疾人教育条例》上升为《特殊教育法》的建议',
      author: '刘素英',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-012',
      title: '关于加强未成年人司法社会支持体系建设的建议',
      author: '罗春梅',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-013',
      title:
        '关于在法律中明确“检察机关在履行法律监督职责中发现行政机关违法行使职权或者不行使职权的，可以依照法律规定制发检察建议等督促其纠正”的建议',
      author: '罗春梅',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-014',
      title: '关于加强区县法检部门经费保障的建议',
      author: '乔进双梅',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-015',
      title: '关于做好相对薄弱法院脱薄工作的建议',
      author: '乔进双梅',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-016',
      title: '关于推进涉案企业合规立法的建议',
      author: '全团',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-017',
      title: '关于进一步规范枪支认定及管理的建议',
      author: '尚丽平',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-018',
      title: '关于完善“笑气”社会治理问题的建议',
      author: '李慧',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-019',
      title: '关于加快推进刑事“涉案财物诉讼”立法的建议',
      author: '王树江',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-020',
      title: '关于对银行业以房抵债有关法律适用予以重视并依法保护的建议',
      author: '魏琴',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-021',
      title: '构建高质量公共法律服务体系',
      author: '吴德',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-022',
      title: '关于深入推进涉案企业合规改革的建议',
      author: '杨心平',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-023',
      title: '关于进一步规范涉案企业合规适用的建议',
      author: '郑功成',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-024',
      title: '关于完善成年监护体系保障特殊群体权益的建议',
      author: '郑喆轩',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-025',
      title: '关于加大扶持民营企业科技创新的建议',
      author: '耿福能',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-026',
      title: '关于积极推动民营企业新时代高质量发展的建议',
      author: '戴学斌',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-027',
      title: '关于大力挖掘弘扬红色法治文化的提案',
      author: '',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-028',
      title: '关于规范法律咨询公司的提案',
      author: '',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-029',
      title: '关于适时修改《中小企业促进法》的提案',
      author: '',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-030',
      title:
        '关于适时修改中小企业促进法的提案；加快推进数据基础制度法律的立法进程，推动数字变革赋能社会发展',
      author: '',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-plan-001',
      title: '关于修订和继续执行移民后期扶持相关政策的建议',
      author: '郑望春',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-002',
      title: '关于给予全国革命老区重点城市巴中精准扶持电价政策的建议',
      author: '戴学斌',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-003',
      title: '关于支持四川省广元市创建国家物流枢纽承载城市的建议',
      author: '董里',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-004',
      title: '关于支持泸州建设“一带一路”及长江经济带战略支点城市的建议',
      author: '董伟',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-005',
      title: '关于支持泸州市创建国家创新型城市的建议',
      author: '董伟',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-006',
      title: '关于将沿江货运铁路重庆经泸州至宜宾段项目纳入国省规划的建议',
      author: '董伟',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-007',
      title: '关于给予高寒高海拔城镇供气供暖供氧政策支持的建议',
      author: '冯发贵',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-008',
      title: '关于加快电力通道建设的建议',
      author: '冯发贵',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-009',
      title: '关于将阿坝州第三机场纳入《全国民用运输机场布局规划》的建议',
      author: '格西王母',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-010',
      title: '关于恳请支持东出北上国际陆港枢纽的建议',
      author: '苟兴龙',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-011',
      title: '关于支持高铁建设用地保障等事项的建议',
      author: '苟兴龙',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-012',
      title: '关于支持四川打造国家战略产业备份基地更好建设国家战略腹地的建议',
      author: '黄河',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-013',
      title: '关于加快推进四川甘孜涉藏农牧区光伏独立供电农网延伸改造的建议',
      author: '江吉村',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-014',
      title: '关于大力支持建设“川滇藏”国家能源安全“大后方”的建议',
      author: '里赞',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-015',
      title: '关于稳定可再生能源补贴政策 维护政府公信力的建议',
      author: '刘汉元',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-016',
      title: '关于加强工业固废磷石膏无害化处理及综合应用的建议',
      author: '吕祖艳',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-017',
      title: '关于支持达州设立国内首个海相深部钾盐资源开发利用试验区的建议',
      author: '严卫东',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-018',
      title: '关于支持达州高新区创建国家高新区的建议',
      author: '吕祖艳',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-019',
      title: '关于推动新能源高质量发展，助力新型电力系统加快构建的建议',
      author: '蒙媛',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-020',
      title: '关于强化空调负荷优化管理助力电力安全可靠供应的建议',
      author: '蒙媛',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-021',
      title: '关于加快推动东西部协作产业转移的建议',
      author: '欧阳梅',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-022',
      title: '关于将真空技术产业列为国家战略产业的建议',
      author: '欧阳梅',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-023',
      title: '关于进一步支持川藏经济协作试验区加快建设的建议',
      author: '彭映梅',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-024',
      title: '关于加速推进社会信用建设立法规范信用信息管理的建议',
      author: '朱永繁',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-025',
      title: '关于加强国家战略腹地能源保障进一步提高四川省能源保供能力的建议',
      author: '全团建议',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-026',
      title: '关于拓展深化成都西部片区国家城乡融合发展试验区的建议',
      author: '全团',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-027',
      title: '关于加快长江上游—金沙江下游千公里航运体系建设的建议',
      author: '全团',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-028',
      title: '关于恳请国家发改委支持江安县古贤坝大桥',
      author: '任敏',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-029',
      title: '关于加强数字政府应用和场景建设加快构建以信用为依托的经济治理体系的建议',
      author: '施小琳',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-030',
      title: '关于支持四川省自贡市创建国家物流枢纽承载城市的建议',
      author: '李慧',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-031',
      title: '天然气产地就地高效转化利用',
      author: '曾洪扬',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-032',
      title:
        '关于支持在全国革命老区重点城市巴中探索建立天然气、石油等资源开发新模式和利益共享机制的建议',
      author: '汪其德',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-033',
      title: '关于推广公园城市规划建设模式的建议',
      author: '王麒',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-034',
      title: '关于进一步统筹推动长江经济带高质量发展的建议',
      author: '王麒',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-035',
      title: '关于进一步改造老旧厂区矿区的建议',
      author: '王晓梅',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-036',
      title: '关于支持阿坝州水网规划纳入国家水网规划的建议',
      author: '新甲旦真',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-037',
      title: '关于支持成都市进一步加大新时代战略大后方建设力度的建议',
      author: '许强',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-038',
      title: '关于做好移民后扶相关工作的建议',
      author: '晏鲁作',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-039',
      title: '关于加快推进边远农牧区光伏独立供电农网延伸改造的建议',
      author: '余德春',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-040',
      title: '关于持续加大对国家城乡融合发展试验区建设支持力度的建议',
      author: '余绍容',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-041',
      title: '关于支持宜宾—泸州联合申报国家综合货运枢纽补链强链城市的建议（联合建议）',
      author: '余先河',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-042',
      title: '关于制定出台支持攀枝花钒钛产业电价政策的建议',
      author: '邹明',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-043',
      title: '关于出台川陕革命老区协同推进高质量发展实施方案的建议',
      author: '高鹏凌',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-044',
      title: '关于打造优势产业树立特色品牌 实现共同富裕的建议',
      author: '耿福能',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-045',
      title: '关于加强川西南地区大中型水利水库建设解决用水时空不均问题的建议',
      author: '郑望春',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-046',
      title: '关于支持汉源县建设旭家沟水库的建议',
      author: '郑望春',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-047',
      title: '关于加快建立嘉陵江联合调度机制的建议',
      author: '董里',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-048',
      title: '关于加快完善基层水利设施建设的建议',
      author: '李君',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-051',
      title: '关于加强农田水利设施建设管护的建议',
      author: '王晓梅',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-052',
      title: '关于巩固提升农村安全饮水工程的建议',
      author: '余德春',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-053',
      title: '关于支持乌蒙山区叙永县、古蔺县大型水利工程建设的建议',
      author: '余先河',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-054',
      title: '关于地震断裂带房屋避险搬迁的建议',
      author: '郑望春',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-055',
      title: '关于地质灾害避险搬迁补偿机制和补助标准的建议',
      author: '郑望春',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-056',
      title: '关于支持达州天然气锂钾资源开发利用的建议',
      author: '苟兴龙',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-057',
      title: '关于支持达州宣汉建设全国百万吨级钾肥基地的建议',
      author: '胡晓玲',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-058',
      title: '关于支持水面光伏项目发展，促进土地资源复合利用的建议',
      author: '刘汉元',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-059',
      title: '关于扩大农村集体经营性建设用地入市试点范围的建议',
      author: '汪其德',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-060',
      title: '关于返还阿坝州探矿权出让收入资金的建议',
      author: '王树明',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-061',
      title: '关于规范国内矿产粗铜新增产能，推动铜产业高质量发展的建议',
      author: '奚正平',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-062',
      title: '关于增加地质灾害避险搬迁补助标准的建议',
      author: '严卫东',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-063',
      title: '关于支持达州设立国内首个深部海相钾盐资源开发利用试验区的建议',
      author: '严卫东',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-064',
      title: '关于鼓励建设钒钛磁铁矿非高炉冶炼示范线的建议',
      author: '邹明',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-fin-001',
      title: '关于调整个人所得税税率与级数的建议',
      author: '庹庆明',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-002',
      title: '关于给予全国革命老区重点城市巴中差异化转移支付政策的建议',
      author: '戴学斌',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-003',
      title: '关于增加中央财政转移支付用于基层医疗机构医务人员全额拨款绩效管理的建议',
      author: '董伟',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-004',
      title: '关于优化个人所得税税制的建议',
      author: '董伟',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-006',
      title:
        '关于取消《中华人民共和国增值税暂行条例》中划分“一般纳税人”和“小规模纳税人”纳税模式的建议',
      author: '李玉梅',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-007',
      title: '关于加快推进增值税税制绿色化改革的建议',
      author: '梁伟',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-008',
      title: '关于推动中央财政补贴覆盖渔业保险的建议',
      author: '刘汉元',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-009',
      title: '对赌协议个人股东业绩补偿金所得税问题建议',
      author: '刘素英',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-010',
      title: '关于增加地质灾害避险搬迁补助标准的建议',
      author: '严卫东',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-011',
      title: '关于废弃电器电子产品基金补贴资金尽快下拨的建议',
      author: '柳江',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-012',
      title: '关于将林竹机械纳入农机购置补贴的建议',
      author: '乔进双梅',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-013',
      title: '关于继续加大财政金融政策力度支持清理拖欠企业账款的建议',
      author: '唐安斌',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-014',
      title: '关于支持阿坝州创建大熊猫国家公园小水电站清退补偿资金的建议',
      author: '王树明',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-015',
      title: '关于进一步降低西部地区高新技术企业企业所得税税率的建议',
      author: '王瑛',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-016',
      title: '关于改进年终奖个税计算方法的建议',
      author: '张祖涛',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-017',
      title: '关于构建全国统一投资者适当性管理平台提升金融市场效率和监管效能的建议',
      author: '董伟',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-020',
      title: '关于加强金融开放监管体系建设的建议',
      author: '梁伟',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-021',
      title: '关于尽快制定出台《金融安全法》的建议',
      author: '梁伟',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-022',
      title: '关于进一步完善西部欠发达地区科技创新和成果转化金融服务体系的建议',
      author: '刘政',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-023',
      title: '关于高度重视并做好存量PPP项目处置工作的建议',
      author: '朱永繁',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-024',
      title: '关于严厉打击分布式小金额网络诈骗的建议',
      author: '尚丽平',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-025',
      title: '关于推进重大自然灾害专门保险立法的建议',
      author: '王树江',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-026',
      title: '关于规范供应链金融发展的建议',
      author: '严宝玉',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-027',
      title: '关于增加地方政府一般债券发行规模的建议',
      author: '杨心平',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-028',
      title: '关于加快建立住宅保险制度的建议',
      author: '郑功成',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-029',
      title: '关于将犬只伤人的刑事责任写入刑法修正案的建议',
      author: '庹庆明',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-030',
      title: '关于尽快制定《预防性环境民事公益诉讼规范》的建议',
      author: '庹庆明',
      link: '',
      topicKey: 'finance',
    },
  ],
  2023: [
    {
      id: '23-tra-001',
      title: '关于支持尽快启动重庆至自贡至雅安铁路建设的建议',
      author: '曾道群',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-002',
      title: '关于支持尽快启动雅安至甘洛铁路建设的建议',
      author: '郑望春',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-003',
      title: '关于出台《川陕革命老区综合交通基础设施振兴发展规划》的建议',
      author: '高鹏凌',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-004',
      title: '关于加快西部陆海新通道西线铁路通道建设的建议',
      author: '四川全团建议',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-005',
      title: '关于将陕西宝鸡—汉中—四川巴中铁路作为区域高速铁路纳入相关规划并加快建设的建议',
      author: '汪其德',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-006',
      title: '关于加快推进民族地区交通基础设施建设的建议',
      author: '余德春',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-007',
      title: '关于将广安至重庆快速通道纳入交通运输部《公路“十四五”发展规划中期调整方案》的建议',
      author: '赵波',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-008',
      title: '关于支持将重庆渝北至四川广安铁路纳入国家铁路专项规划的建议',
      author: '赵波',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-009',
      title: '关于修建“雅安到西宁”铁路的建议',
      author: '',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-010',
      title: '关于加快新成昆高铁规划建设的建议',
      author: '乔进双梅',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-011',
      title: '关于加快G0611张掖至汶川高速公路（四川段）建设的建议',
      author: '王树明',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-012',
      title: '关于将阿坝第三机场纳入《全国民用运输机场布局规划》并尽早开工建设的建议',
      author: '王树明',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-013',
      title: '关于优化中老铁路运行配套政策 加速西部地区融入“一带一路”建设的建议',
      author: '邹明',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-014',
      title: '关于优化中老铁路配套举措加速“一带一路”建设的提案',
      author: '',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-015',
      title: '关于加快西部陆海新通道西线铁路建设的提案',
      author: '',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-016',
      title: '关于在川陕革命老区规划建设成巴安高速铁路的提案',
      author: '',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-017',
      title: '关于推动收费公路高质量发展的提案',
      author: '',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-018',
      title: '关于支持甘孜州骨干高速路网建设的建议',
      author: '',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-019',
      title: '关于建设川渝东北一体化水资源配置工程的提案',
      author: '',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-cy-001',
      title: '关于支持尽快启动重庆至自贡至雅安铁路建设的建议',
      author: '曾道群',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-002',
      title: '关于支持尽快启动雅安至甘洛铁路建设的建议',
      author: '郑望春',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-003',
      title: '关于优化重大生产力布局促进成渝地区双城经济圈建设的建议',
      author: '四川全团建议',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-004',
      title: '关于健全国家层面推动成渝地区双城经济圈建设工作推进机制的建议',
      author: '四川全团建议',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-005',
      title: '关于设立成渝地区双城经济圈国家文化和旅游创新改革试验区的建议',
      author: '何延政',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-006',
      title: '关于支持成渝地区双城经济圈海关特殊监管场所建设的建议',
      author: '刘延安',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-007',
      title: '关于鼓励支持海外留学归国人员和侨资企业参与成渝双城经济圈建设的建议',
      author: '王麟',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-008',
      title: '关于加快川渝执法司法一体化进程的建议',
      author: '王瑛',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-009',
      title: '关于打造川渝地区天然气与新能源绿色融合发展新模式的建议',
      author: '文绍牧',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-010',
      title: '关于建立成渝地区双城经济圈建设高规格工作机制的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-011',
      title: '关于进一步完善成渝地区双城经济圈对外通道的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-012',
      title: '关于成渝地区双城经济圈部分县化解隐性债务的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-013',
      title: '关于建立成渝地区双城经济圈建设高规格工作机制的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-014',
      title: '关于进一步完善成渝地区双城经济圈对外通道的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-015',
      title: '关于成渝地区双城经济圈部分县化解隐性债务的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-016',
      title: '关于布局综合性国家科学中心的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-017',
      title: '关于加快西部科学城建设的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-018',
      title: '关于建立成渝地区双城经济圈建设高规格工作机制的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-019',
      title: '关于进一步完善成渝地区双城经济圈对外通道的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-020',
      title: '关于进一步完善成渝地区双城经济圈对外通道的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-021',
      title: '关于建设川渝东北一体化水资源配置工程的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-022',
      title: '关于成渝地区双城经济圈部分县化解隐性债务的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-023',
      title: '关于建立成渝地区双城经济圈建设高规格工作机制的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-024',
      title: '关于进一步完善成渝地区双城经济圈对外通道的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-025',
      title: '关于成渝地区双城经济圈部分县化解隐性债务的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-026',
      title: '关于川渝地区天然气资源就地高效转化利用的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-ref-004',
      title: '关于支持丝纺行业持续健康发展的建议',
      author: '王丽',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-ref-005',
      title: '关于深化公平竞争，提升民营经济信心的建议',
      author: '戴学斌',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-ref-006',
      title: '关于改进小微企业信贷服务进一步优化营商环境的建议',
      author: '刘延安',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-ref-007',
      title: '关于高度重视解决大型企业拖欠专精特新中小企业账款问题 增强国家科技创新竞争力的再建议',
      author: '刘延安',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-ref-008',
      title: '关于促进汽车消费，提振经济回升的建议',
      author: '王麟',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-ref-009',
      title: '关于精准施策，推进民营经济高质量发展的建议',
      author: '王麟',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-ref-010',
      title: '关于增强民营企业发展信心的建议的提案',
      author: '',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-ref-011',
      title: '关于进一步提升民营企业发展信心的提案',
      author: '',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-ref-012',
      title: '关于支持四川打造参与国际竞争新基地的提案',
      author: '',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-ref-013',
      title: '关于促进互联网货运平台企业规范健康发展的提案',
      author: '',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-gr-001',
      title: '关于优化进口饲用粮配额分配机制的建议',
      author: '刘汉元',
      link: '',
      topicKey: 'grain',
    },
    {
      id: '23-gr-002',
      title: '关于建设新时代更高水平“天府粮仓”的建议',
      author: '黄河',
      link: '',
      topicKey: 'grain',
    },
    {
      id: '23-gr-003',
      title: '关于加快建设川渝地区大豆良种繁育基地更好维护国家粮食安全的建议',
      author: '欧阳梅',
      link: '',
      topicKey: 'grain',
    },
    {
      id: '23-gr-004',
      title: '关于支持四川建设新时代更高水平“天府粮仓”和擦亮农业大省“金字招牌”的建议',
      author: '四川全团建议',
      link: '',
      topicKey: 'grain',
    },
    {
      id: '23-gr-005',
      title: '关于持续加大高标准农田建设投入力度的建议',
      author: '四川全团建议',
      link: '',
      topicKey: 'grain',
    },
    {
      id: '23-gr-007',
      title: '关于加大农业投入的建议',
      author: '',
      link: '',
      topicKey: 'grain',
    },
    {
      id: '23-gr-008',
      title: '关于支持雅安全域现代农业绿色发展的建议',
      author: '',
      link: '',
      topicKey: 'grain',
    },
    {
      id: '23-gr-009',
      title: '关于高效实施好高标准农田建设工程的建议',
      author: '曾道群',
      link: '',
      topicKey: 'grain',
    },
    {
      id: '23-gr-010',
      title: '关于加快完善丘陵地区农田灌溉“最后一公里”的建议',
      author: '李玉梅',
      link: '',
      topicKey: 'grain',
    },
    {
      id: '23-gr-011',
      title: '关于打造新时代更高水平“天府粮仓”的提案',
      author: '',
      link: '',
      topicKey: 'grain',
    },
  ],
}
export const topicDetailByYear = {
  2025: [
    {
      id: '25-1',
      content: '47件民生建议是四川增进民生福祉、回应群众期盼的温度',
      tag: '民生',
      topicKey: 'livelihood',
    },
    {
      id: '25-2',
      content: '8件生态保护建议是四川加快绿色转型、筑牢生态屏障的进度',
      tag: '生态保护',
      topicKey: 'ecology',
    },
    {
      id: '25-3',
      content: '8件文化旅游建议是四川彰显文化魅力、传播四川声音的热度',
      tag: '文化旅游',
      topicKey: 'culture',
    },
    {
      id: '25-4',
      content: '2件新质生产力建议是四川塑造发展新动能、构建现代化产业体系的精度',
      tag: '新质生产力',
      topicKey: 'industry',
    },
  ],
  2024: [
    {
      id: '24-1',
      content: '138件“四个发力”建议是四川把握战略定位、推动全面发展的力度',
      tag: '四个发力',
      topicKey: 'four',
    },
    {
      id: '24-2',
      content: '30件法治四川建议是四川推进依法治理、规范社会运行的法度',
      tag: '法治四川',
      topicKey: 'law',
    },
    {
      id: '24-3',
      content: '64件发展规划建议是四川谋划长远发展、锚定未来方向的高度',
      tag: '发展规划',
      topicKey: 'plan',
    },
    {
      id: '24-4',
      content: '28件财税金融建议是四川强化要素保障、夯实发展根基的强度',
      tag: '财政金融',
      topicKey: 'finance',
    },
  ],
  2023: [
    {
      id: '23-1',
      content: '19件交通建议是四川加速内联外畅、建设现代化综合交通体系的广度',
      tag: '交通',
      topicKey: 'traffic',
    },
    {
      id: '23-2',
      content: '28件成渝地区双城经济圈建议是四川深化川渝协同、唱好“双城记”的跨度',
      tag: '成渝地区双城经济圈',
      topicKey: 'chengyu',
    },
    {
      id: '23-3',
      content: '15件改革开放建议是四川破除发展壁垒、提升开放能级的态度',
      tag: '改革开放',
      topicKey: 'reform',
    },
    {
      id: '23-4',
      content: '11件天府粮仓建议是四川保障粮食安全、夯实农业根基的尺度',
      tag: '天府粮仓',
      topicKey: 'grain',
    },
  ],
}
export const topicAuthorList = [
  {
    id: "author-001",
    author: "庹庆明",
    title: "全国人大代表庹庆明：怀揣着一本群众幸福的“密码本”",
    link: "https://ya.newssc.org/system/20250228/003574225.html",
    year: "2025",
  },
  {
    id: "author-002",
    author: "庹庆明",
    title: "贯彻实施《中华人民共和国国家公园法》座谈会暨第三届国家公园司法保护协作联盟会议召开",
    link: "https://scnews.newssc.org/system/20251113/001569936.html",
    year: "2025",
  },
  {
    id: "author-003",
    author: "庹庆明",
    title: "开局之年的全国两会，四川代表委员关注哪些事？",
    link: "https://sichuan.scol.com.cn/ggxw/202603/83215610.html",
    year: "2026",
  },
  {
    id: "author-004",
    author: "庹庆明",
    title: "全国人大代表庹庆明：做个有心的人大代表",
    link: "http://sc.people.com.cn/n2/2025/0225/c345458-41146352.html",
    year: "2025",
  },
  {
    id: "author-005",
    author: "庹庆明",
    title: "两会新华解码丨政府工作报告首提“逐步推行免费学前教育”，将如何落实？",
    link: "https://www.news.cn/20250305/36b5271530f644beb8ec2d07e78d01a8/c.html",
    year: "2025",
  },
  {
    id: "author-006",
    author: "曾娜",
    title: "全国人大代表曾娜：要以责任为关键词 深耕行业领域关注国计民生 | 履职记",
    link: "https://scnews.newssc.org/system/20250301/001509763.html",
    year: "2025",
  },
  {
    id: "author-007",
    author: "曾娜",
    title: "曾娜代表：传承白酒酿制技艺 加强民族品牌宣传",
    link: "http://finance.people.com.cn/n1/2025/0308/c1004-40434257.html",
    year: "2025",
  },
  {
    id: "author-008",
    author: "曾娜",
    title: "曾娜代表：加强文化遗产保护 助推中国优秀传统文化走向世界",
    link: "http://finance.people.com.cn/n1/2024/0307/c1004-40191057.html",
    year: "2024",
  },
  {
    id: "author-009",
    author: "曾娜",
    title: "曾娜代表：推进“互联网+非遗”模式创新 保护传统非遗文物",
    link: "http://finance.people.com.cn/n1/2023/0307/c1004-32638931.html",
    year: "2023",
  },
  {
    id: "author-010",
    author: "曾娜",
    title: "曾娜代表：加强酒类知识产权保护 探索传统产业绿色循环新模式",
    link: "http://finance.people.com.cn/n1/2022/0310/c1004-32371255.html",
    year: "2022",
  },
  {
    id: "author-011",
    author: "李世亮",
    title: "四川十大法治人物”巡回宣讲活动在乐山举行",
    link: "https://leshan.scol.com.cn/ztls/202504/83185080.html",
    year: "2025",
  },
  {
    id: "author-012",
    author: "李世亮",
    title: "李世亮代表：让更多律师参与到公共法律服务中 让老百姓享受高效优质的法律服务",
    link: "http://sc.people.com.cn/n2/2025/0307/c345167-41156842.html",
    year: "2025",
  },
  {
    id: "author-013",
    author: "李世亮",
    title: "全国人大代表李世亮：柔性执法为市场主体添活力、增动力",
    link: "http://sc.people.com.cn/n2/2023/0303/c345167-40323042.html",
    year: "2023",
  },
  {
    id: "author-014",
    author: "刘素英",
    title: "刘素英代表：乘教育改革东风 谱优质发展新篇",
    link: "http://ent.people.com.cn/n1/2025/0310/c1012-40435964.html",
    year: "2025",
  },
  {
    id: "author-015",
    author: "刘素英",
    title: "全国人大代表刘素英：四省市协同立法，共护千年蜀道丨两会最前线",
    link: "https://scnews.newssc.org/system/20250310/001511734.html",
    year: "2025",
  },
  {
    id: "author-016",
    author: "刘素英",
    title: "刘素英代表：凝聚巾帼力量 共建友好城市",
    link: "http://sc.people.com.cn/n2/2024/0318/c345458-40779200.html",
    year: "2024",
  },
  {
    id: "author-017",
    author: "刘素英",
    title: "刘素英代表：聚焦实施教育提质工程 努力办好人民满意的教育",
    link: "http://lianghui.people.com.cn/2023/n1/2023/0313/c452473-32643537.html",
    year: "2023",
  },
  {
    id: "author-018",
    author: "罗春梅",
    title: "罗春梅任四川省人大常委会副秘书长",
    link: "https://sichuan.scol.com.cn/xwtg/202404/82501633.html",
    year: "2024",
  },
  {
    id: "author-019",
    author: "乔进双梅",
    title: "乔进双梅代表：电力铺就振兴之路，马边迈向致富通途",
    link: "http://sc.people.com.cn/n2/2025/0305/c345167-41154279.html",
    year: "2025",
  },
  {
    id: "author-020",
    author: "乔进双梅",
    title: "乔进双梅：做好“彝绣＋” “绣”出乡村振兴新活力",
    link: "http://sc.people.com.cn/n2/2024/0306/c345509-40766459.html",
    year: "2024",
  },
  {
    id: "author-021",
    author: "乔进双梅",
    title: "全国人大代表乔进双梅：呵护非遗传承的税收“巧手”",
    link: "http://sc.people.com.cn/n2/2023/0303/c379469-40323750.html",
    year: "2023",
  },
  {
    id: "author-022",
    author: "乔进双梅",
    title: "36项四川非遗登上央视春晚宜宾分会场——你知道四川非遗的璀璨多姿吗？",
    link: "https://ent.scol.com.cn/wh/202602/83209037.html",
    year: "2026",
  },
  {
    id: "author-023",
    author: "乔进双梅",
    title: "全国人大代表乔进双梅：彝绣针功夫 绣出真精彩｜履职记",
    link: "https://scnews.newssc.org/system/20250302/001509892.html",
    year: "2025",
  },
  {
    id: "author-024",
    author: "尚丽平",
    title: "全国人大代表尚丽平：建议推进“双一流”高校建设扩容｜两会最前线",
    link: "https://scnews.newssc.org/system/20250308/001511387.html",
    year: "2025",
  },
  {
    id: "author-025",
    author: "尚丽平",
    title: "四川省人民政府发布一批人事任免 涉厅级领导职务",
    link: "https://scnews.newssc.org/system/20251111/001569373.html",
    year: "2025",
  },
  {
    id: "author-026",
    author: "王树江",
    title: "全国人大代表王树江：推动国家公园立法 促进生态文明建设",
    link: "http://sc.people.com.cn/n2/2022/0310/c345509-35168017.html",
    year: "2022",
  },
  {
    id: "author-027",
    author: "王树江",
    title: "全国人大代表王树江：建立性侵害未成年人精神损害赔偿制度",
    link: "http://sc.people.com.cn/n2/2022/0309/c345509-35166215.html",
    year: "2022",
  },
  {
    id: "author-028",
    author: "王树江",
    title: "省十四届人大常委会举行第二十三次会议，任命陈志君为省高级人民法院副院长，决定陈志君为省高级人民法院代理院长",
    link: "https://sichuan.scol.com.cn/ggxw/202601/83186771.html",
    year: "2026",
  },
  {
    id: "author-029",
    author: "王树江",
    title: "陈志君：以高质量司法护航“十五五”时期四川高质量发展",
    link: "https://www.scol.com.cn/zlts_ss/202512/83182068.html",
    year: "2025",
  },
  {
    id: "author-030",
    author: "魏琴",
    title: "镜观两会丨四川女代表女委员 全国两会展风采",
    link: "https://sichuan.scol.com.cn/ggxw/202403/82481262.html",
    year: "2024",
  },
  {
    id: "author-031",
    author: "魏琴",
    title: "全国人大代表魏琴：大学生就业创业路上，税务一路相伴",
    link: "http://sc.people.com.cn/n2/2023/0222/c345167-40311453.html",
    year: "2023",
  },
  {
    id: "author-032",
    author: "吴德",
    title: "全国人大代表吴德：蓄能农业新质生产力",
    link: "http://sc.people.com.cn/n2/2024/0306/c345509-40766911.html",
    year: "2024",
  },
  {
    id: "author-033",
    author: "吴德",
    title: "全国人大代表吴德：这项技术三次写入中央一号文件 有效降低大豆对外依赖｜分享四川",
    link: "https://scnews.newssc.org/system/20250307/001511060.html",
    year: "2025",
  },
  {
    id: "author-034",
    author: "吴德",
    title: "全国人大代表吴德：回应农民期盼，为丘陵山区研发“智慧铁牛”丨全国两会“问答对”@代表委员",
    link: "https://sichuan.scol.com.cn/ggxw/202603/83214127.html",
    year: "2026",
  },
  {
    id: "author-035",
    author: "杨心平",
    title: "文旅产业如何从“网红”变“长红”？",
    link: "http://sc.people.com.cn/n2/2024/0309/c379470-40769787.html",
    year: "2024",
  },
  {
    id: "author-036",
    author: "杨心平",
    title: "两会好声音丨全国人大代表杨心平：建议支持乐山建设世界重要旅游目的地",
    link: "https://sichuan.scol.com.cn/ggxw/202503/82914269.html",
    year: "2025",
  },
  {
    id: "author-037",
    author: "杨心平",
    title: "代表委员履职记丨全国人大代表杨心平：从基层发现问题，才能多角度精准建言献策",
    link: "https://sichuan.scol.com.cn/ggxw/202502/82908795.html",
    year: "2025",
  },
  {
    id: "author-038",
    author: "杨心平",
    title: "全国人大代表杨心平：人民记者和人大代表都是为民发声｜履职记",
    link: "https://scnews.newssc.org/system/20250302/001509889.html",
    year: "2025",
  },
  {
    id: "author-039",
    author: "郑功成",
    title: "人民日报谈破除“三十五岁门槛”：让年龄不再成为标签",
    link: "https://focus.scol.com.cn/zgsz/202503/82916326.html",
    year: "2025",
  },
  {
    id: "author-040",
    author: "郑功成",
    title: "央媒看四川 | 全国人大代表郑功成：以“如我在诉”意识办好民生案",
    link: "https://sichuan.scol.com.cn/tfrm/202503/82914836.html",
    year: "2025",
  },
  {
    id: "author-041",
    author: "郑功成",
    title: "郑功成代表：人均再提高30元 医保“含金量”持续提升",
    link: "http://lianghui.people.com.cn/2025/n1/2025/0308/c460111-40434369.html",
    year: "2025",
  },
  {
    id: "author-042",
    author: "郑功成",
    title: "郑功成：让养老服务更有质量 满足老年人多层次养老需求",
    link: "http://society.people.com.cn/n1/2023/1010/c1008-40092521.html",
    year: "2023",
  },
  {
    id: "author-043",
    author: "郑喆轩",
    title: "郑喆轩代表：推动考古与公众“双向奔赴”",
    link: "http://ent.people.com.cn/n1/2025/0310/c1012-40435318.html",
    year: "2025",
  },
  {
    id: "author-044",
    author: "郑喆轩",
    title: "穿行高山河谷 探寻远古文明（讲述·赓续历史文脉 谱写当代华章）",
    link: "http://society.people.com.cn/n1/2025/0318/c1008-40440891.html",
    year: "2025",
  },
  {
    id: "author-045",
    author: "郑喆轩",
    title: "央媒看四川丨四川省濛溪河遗址考古队努力重现旧石器时代古人类生活图景 揭秘“百科全书”式遗址",
    link: "https://sichuan.scol.com.cn/ggxw/202601/83197849.html",
    year: "2026",
  },
  {
    id: "author-046",
    author: "郑喆轩",
    title: "全国人大代表郑喆轩：让文物的光芒穿越历史点亮未来丨代表委员履职记",
    link: "https://scnews.newssc.org/system/20250221/001508327.html",
    year: "2025",
  },
  {
    id: "author-047",
    author: "郑喆轩",
    title: "郑喆轩：借助科技与网络的力量 考古如一汪春水注入精神文明建设中",
    link: "https://scnews.newssc.org/system/20240828/001471547.html",
    year: "2024",
  },
  {
    id: "author-048",
    author: "耿福能",
    title: "耿福能代表——从“靠天吃饭”到“靠技增收”丨代表委员履职故事",
    link: "https://sichuan.scol.com.cn/ggxw/202602/83207476.html",
    year: "2026",
  },
  {
    id: "author-049",
    author: "戴学斌",
    title: "全国人大代表戴学斌：让金融活水精准灌溉民营经济发展｜两会最前线",
    link: "https://scnews.newssc.org/system/20250310/001511741.html",
    year: "2025",
  },
  {
    id: "author-050",
    author: "戴学斌",
    title: "全国人大代表戴学斌建议：完善生态保护补偿制度",
    link: "https://bz.newssc.org/system/20250312/003576373.html",
    year: "2025",
  },
  {
    id: "author-051",
    author: "戴学斌",
    title: "全国人大代表戴学斌建议：提高经济欠发达地区医疗救助国家财政补助标准",
    link: "https://bz.newssc.org/system/20250310/003575806.html",
    year: "2025",
  },
  {
    id: "author-052",
    author: "戴学斌",
    title: "全国人大代表、蓝润集团董事长戴学斌：发展新质生产力，传统产业需“迎风上”",
    link: "http://sc.people.com.cn/n2/2025/0308/c345167-41157855.html",
    year: "2025",
  },
  {
    id: "author-053",
    author: "廖文彬",
    title: "廖文彬：推动“三服务”工作走深走实",
    link: "http://sc.people.com.cn/cpc/n2/2026/0228/c392659-41511685.html",
    year: "2026",
  },
  {
    id: "author-054",
    author: "廖文彬",
    title: "廖文彬：因地制宜做好城市规划建设管理",
    link: "http://sc.people.com.cn/cpc/n2/2025/0930/c392659-41369819.html",
    year: "2025",
  },
  {
    id: "author-055",
    author: "廖文彬",
    title: "廖文彬：把雅安的工作做好，把雅安的事情办好",
    link: "http://sc.people.com.cn/cpc/n2/2025/0801/c392659-41309956.html",
    year: "2025",
  },
  {
    id: "author-056",
    author: "廖文彬",
    title: "廖文彬：把规划变为蓝图、把蓝图变为现实，关键在实干",
    link: "http://sc.people.com.cn/cpc/n2/2025/1104/c392659-41401076.html",
    year: "2025",
  },
  {
    id: "author-057",
    author: "罗先刚",
    title: "C视频丨中国工程院院士罗先刚：科学既需要“于无声处听惊雷”的敏锐，更要有“甘坐十年冷板凳”的定力丨关注省科学技术奖",
    link: "https://sichuan.scol.com.cn/ggxw/202508/83109848.html",
    year: "2025",
  },
  {
    id: "author-058",
    author: "吴忠跃",
    title: "两会好声音丨全国人大代表吴忠跃：建设中国发动机博物馆 开展航空发动机科普教育",
    link: "https://sichuan.scol.com.cn/ggxw/202303/58829417.html",
    year: "2023",
  },
  {
    id: "author-059",
    author: "尧德中",
    title: "尧德中代表：推动脑机接口重点应用于神经系统疾病诊疗",
    link: "http://lianghui.people.com.cn/2026/n1/2026/0304/c461828-40674318.html",
    year: "2026",
  },
  {
    id: "author-060",
    author: "尧德中",
    title: "成都市第四人民医院：打呼噜不等于睡得香，智慧医疗助力睡眠健康",
    link: "http://sc.people.com.cn/n2/2025/0320/c379469-41170189.html",
    year: "2025",
  },
  {
    id: "author-061",
    author: "尧德中",
    title: "电子科技大学教授尧德中当选古巴科学院外籍院士",
    link: "https://sichuan.scol.com.cn/ggxw/202509/83120143.html",
    year: "2025",
  },
  {
    id: "author-062",
    author: "尧德中",
    title: "西部首个脑机接口中试平台在蓉成立",
    link: "https://scnews.newssc.org/system/20250723/001542472.html",
    year: "2025",
  },
  {
    id: "author-063",
    author: "邹明",
    title: "全国人大代表邹明：税惠持续加力，为攀钢的制造攻坚与科技创新注入了强劲动能",
    link: "http://sc.people.com.cn/n2/2025/0226/c345167-41147077.html",
    year: "2025",
  },
  {
    id: "author-064",
    author: "杨武云",
    title: "全国人大代表杨武云：建议扩建四川夏繁“硅谷”",
    link: "https://sichuan.scol.com.cn/tfrm/202503/82913051.html",
    year: "2025",
  },
  {
    id: "author-065",
    author: "杨武云",
    title: "四川代表团集中审议政府工作报告：团结奋斗推动中国式现代化“乘风破浪”",
    link: "https://sichuan.scol.com.cn/ggxw/202503/82912388.html",
    year: "2025",
  },
  {
    id: "author-066",
    author: "杨武云",
    title: "全国人大代表杨武云：构建种业创新高地 服务四川 辐射西南 支撑全国｜两会最前线",
    link: "https://scnews.newssc.org/system/20250308/001511391.html",
    year: "2025",
  },
  {
    id: "author-067",
    author: "杨武云",
    title: "振兴乡村 绿色经济——九三学社眉山市委赴彭山区调研葡萄产业",
    link: "https://ms.newssc.org/system/20210717/003167967.html",
    year: "2021",
  },
  {
    id: "author-068",
    author: "钟波",
    title: "全国人大代表钟波：税务部门行政审批制度改革，让企业感受到营商环境优化的切实成果",
    link: "http://sc.people.com.cn/n2/2025/0302/c379469-41151175.html",
    year: "2025",
  },
  {
    id: "author-069",
    author: "钟波",
    title: "全国人大代表钟波：建议制定并发布家用智能投影机强制性国家标准",
    link: "http://sc.people.com.cn/n2/2023/0307/c345167-40327654.html",
    year: "2023",
  },
  {
    id: "author-070",
    author: "郑望春",
    title: "全国人大代表郑望春：带火“悬崖古村”村游的流量密码",
    link: "http://pic.people.com.cn/n1/2026/0302/c1016-40672936.html",
    year: "2026",
  },
  {
    id: "author-071",
    author: "郑望春",
    title: "全国人大代表郑望春：做“天梯村”的致富领路人",
    link: "http://pic.people.com.cn/n1/2023/0304/c452490-32636460.html",
    year: "2023",
  },
  {
    id: "author-072",
    author: "郑望春",
    title: "【新时代·答卷人】郑望春： 三小时变成三分钟 架起通天路的古路村摩托三轮畅快跑",
    link: "https://scnews.newssc.org/system/20220529/001271072.html",
    year: "2022",
  },
  {
    id: "author-073",
    author: "郑望春",
    title: "雅安：“古路村”的平安守护",
    link: "https://local.newssc.org/system/20240326/003494519.htm",
    year: "2024",
  },
  {
    id: "author-074",
    author: "曹天兰",
    title: "全国人大代表曹天兰：税惠让研发信心更足",
    link: "http://sc.people.com.cn/n2/2023/0224/c379469-40314743.html",
    year: "2023",
  },
  {
    id: "author-075",
    author: "曹天兰",
    title: "曹天兰代表：发展新质生产力 推动装备制造业高端化、绿色化、智能化发展",
    link: "http://sc.people.com.cn/n2/2025/0305/c345167-41154071.html",
    year: "2025",
  },
  {
    id: "author-076",
    author: "曹天兰",
    title: "曹天兰代表：支持中小型燃气轮机现代产业链建设 推动新质生产力加快发展",
    link: "http://sc.people.com.cn/n2/2024/0229/c345167-40760700.html",
    year: "2024",
  },
  {
    id: "author-077",
    author: "曹天兰",
    title: "全国人大代表曹天兰：建议设立中小型燃气轮机现代产业链链长 推动制造业高质量发展",
    link: "http://sc.people.com.cn/n2/2023/0307/c407367-40327241.html",
    year: "2023",
  },
  {
    id: "author-078",
    author: "陈光浩",
    title: "陈光浩代表：因为一个人爱上一座城 《哪吒2》电影的诞生地四川将迎来文旅新高潮",
    link: "http://sc.people.com.cn/n2/2025/0307/c345509-41157130.html",
    year: "2025",
  },
  {
    id: "author-079",
    author: "陈光浩",
    title: "全国人大代表陈光浩：以中国式现代化引领乐山现代化建设",
    link: "http://sc.people.com.cn/n2/2023/0309/c345509-40329941.html",
    year: "2023",
  },
  {
    id: "author-080",
    author: "陈光浩",
    title: "全国人大代表陈光浩：因为哪吒爱上四川｜分享四川",
    link: "https://scnews.newssc.org/system/20250307/001511110.html",
    year: "2025",
  },
  {
    id: "author-081",
    author: "陈张铭",
    title: "自贡市副市长陈张铭率队调研市三医院高质量发展工作",
    link: "https://local.newssc.org/system/20250211/003571044.htm",
    year: "2025",
  },
  {
    id: "author-082",
    author: "陈张铭",
    title: "全国人大代表、自贡市副市长陈张铭：禁止“油改气”要因地制宜，不能赶潮流丢实惠",
    link: "http://sc.people.com.cn/n2/2022/0308/c345509-35164278.html",
    year: "2022",
  },
  {
    id: "author-083",
    author: "翟刚",
    title: "开局他们说丨翟刚：在良好开局中坚决扛起工业担当",
    link: "https://sichuan.scol.com.cn/ggxw/202602/83212098.html",
    year: "2026",
  },
  {
    id: "author-084",
    author: "翟刚",
    title: "全省工业和信息化工作会议在成都召开",
    link: "https://scnews.newssc.org/system/20260113/001583832.html",
    year: "2026",
  },
  {
    id: "author-085",
    author: "苟兴龙",
    title: "开局之年的全国两会，四川代表委员关注哪些事？",
    link: "https://sichuan.scol.com.cn/ggxw/202603/83215610.html",
    year: "2026",
  },
  {
    id: "author-086",
    author: "苟兴龙",
    title: "全国人大代表苟兴龙：构建人工智能教育生态 培育未来创新人才方阵｜两会最前线",
    link: "https://scnews.newssc.org/system/20250311/001512050.html",
    year: "2025",
  },
  {
    id: "author-087",
    author: "刘汉元",
    title: "全国人大代表、通威集团董事局主席刘汉元：建议设立十万亿股市平准基金和十万亿楼市稳定基金",
    link: "https://finance.newssc.org/system/20250305/003575161.html",
    year: "2025",
  },
  {
    id: "author-088",
    author: "刘汉元",
    title: "刘汉元代表：建议支持我国“新三样”出海",
    link: "http://sc.people.com.cn/n2/2025/0304/c345167-41152879.html",
    year: "2025",
  },
  {
    id: "author-089",
    author: "刘汉元",
    title: "刘汉元代表：加快推进新型电力系统建设",
    link: "http://sc.people.com.cn/n2/2025/0307/c345167-41156625.html",
    year: "2025",
  },
  {
    id: "author-090",
    author: "刘汉元",
    title: "刘汉元代表：建立电网碳排放因子数据库 完善绿色电力交易机制",
    link: "http://sc.people.com.cn/n2/2024/0305/c345509-40765380.html",
    year: "2024",
  },
  {
    id: "author-091",
    author: "刘汉元",
    title: "刘汉元代表：支持水面光伏项目发展，促进土地资源高效复合利用",
    link: "http://sc.people.com.cn/n2/2024/0307/c345509-40768056.html",
    year: "2024",
  },
  {
    id: "author-092",
    author: "马奎",
    title: "全国人大代表马奎：充分释放工业互联网及5G产业科技创新驱动力",
    link: "http://sc.people.com.cn/n2/2023/0310/c345509-40331857.html",
    year: "2023",
  },
  {
    id: "author-093",
    author: "马奎",
    title: "全国人大代表、中国移动四川公司总经理马奎：推动县域工业数字化转型 助力打造新质生产力",
    link: "http://sc.people.com.cn/n2/2024/0305/c345509-40765659.html",
    year: "2024",
  },
  {
    id: "author-094",
    author: "彭映梅",
    title: "彭映梅代表：锚定高质量发展首要任务 奋力推进中国式现代化雅安实践",
    link: "http://sc.people.com.cn/n2/2025/0304/c345167-41152958.html",
    year: "2025",
  },
  {
    id: "author-095",
    author: "彭映梅",
    title: "彭映梅代表：高水平建设世界大熊猫文化旅游重要目的地",
    link: "http://sc.people.com.cn/n2/2024/0306/c345509-40766335.html",
    year: "2024",
  },
  {
    id: "author-096",
    author: "彭映梅",
    title: "全国人大代表彭映梅：建设川藏经济协作试验区和世界大熊猫文化旅游重要目的地",
    link: "http://sc.people.com.cn/n2/2023/0306/c345509-40326153.html",
    year: "2023",
  },
  {
    id: "author-097",
    author: "彭映梅",
    title: "全国人大代表彭映梅：雅安高质量发展新步伐 生态优先、绿色发展",
    link: "https://scnews.newssc.org/system/20230310/001347635.html",
    year: "2023",
  },
  {
    id: "author-098",
    author: "王丽",
    title: "代表委员履职记｜全国人大代表王丽：用心用情履职 为基层代好言",
    link: "https://scnews.newssc.org/system/20240220/001431648.html",
    year: "2024",
  },
  {
    id: "author-099",
    author: "何延政",
    title: "何延政赴广安市调研基地建设工作 发挥界别优势 强化结对共建",
    link: "https://gas.newssc.org/system/20250910/003596503.html",
    year: "2025",
  },
  {
    id: "author-100",
    author: "罗振华",
    title: "罗振华代表：推动民族地区高质量发展阿坝典范建设",
    link: "http://sc.people.com.cn/n2/2025/0310/c345167-41159439.html",
    year: "2025",
  },
  {
    id: "author-101",
    author: "罗振华",
    title: "罗振华代表：构建一屏四带、全域生态大美形态，不断续写美丽阿坝新篇章",
    link: "http://sc.people.com.cn/n2/2024/0308/c410112-40769042.html",
    year: "2024",
  },
  {
    id: "author-102",
    author: "罗振华",
    title: "罗振华参加支部党建联建共建活动并讲专题党课",
    link: "https://ab.newssc.org/system/20250704/003590361.html",
    year: "2025",
  },
  {
    id: "author-103",
    author: "吴群刚",
    title: "全国人大代表吴群刚：攀枝花，来一次就会爱上 | 分享四川",
    link: "https://scnews.newssc.org/system/20250307/001511112.html",
    year: "2025",
  },
  {
    id: "author-104",
    author: "吴群刚",
    title: "吴群刚：始终把教育摆在优先发展位置",
    link: "http://sc.people.com.cn/cpc/n2/2025/0930/c392659-41369726.html",
    year: "2025",
  },
  {
    id: "author-105",
    author: "吴群刚",
    title: "吴群刚：推动攀枝花产业版图焕发全新活力",
    link: "http://sc.people.com.cn/cpc/n2/2025/1104/c392659-41400973.html",
    year: "2025",
  },
  {
    id: "author-106",
    author: "吴群刚",
    title: "吴群刚：紧扣发展所需、群众所盼深化共富试验探索",
    link: "http://sc.people.com.cn/cpc/n2/2026/0204/c392659-41492828.html",
    year: "2026",
  },
  {
    id: "author-107",
    author: "吴群刚",
    title: "吴群刚：厚植美丽攀枝花建设的“绿色家底”",
    link: "http://sc.people.com.cn/cpc/n2/2025/0701/c392659-41277868.html",
    year: "2025",
  },
  {
    id: "author-108",
    author: "刘传健",
    title: "全国人大代表刘传健：完善法律体系 确保低空空域无人机安全运行",
    link: "http://sc.people.com.cn/n2/2024/0306/c345509-40766516.html",
    year: "2024",
  },
  {
    id: "author-109",
    author: "刘传健",
    title: "刘传健代表：每一次飞行都承载着使命 保证飞行安全是我的责任",
    link: "http://lianghui.people.com.cn/2024/n1/2024/0305/c458655-40189190.html",
    year: "2024",
  },
  {
    id: "author-110",
    author: "曾洪扬",
    title: "曾洪扬：不断夯实自贡现代化建设的“三农”底座",
    link: "http://sc.people.com.cn/cpc/n2/2026/0228/c392659-41511686.html",
    year: "2026",
  },
  {
    id: "author-111",
    author: "曾洪扬",
    title: "曾洪扬：以民生为本提升幸福成色",
    link: "http://sc.people.com.cn/cpc/n2/2025/1231/c392659-41460303.html",
    year: "2025",
  },
  {
    id: "author-112",
    author: "曾洪扬",
    title: "曾洪扬：持续擦亮“中国灯城”特色文旅名片",
    link: "http://sc.people.com.cn/cpc/n2/2026/0202/c392659-41490855.html",
    year: "2026",
  },
  {
    id: "author-113",
    author: "曾洪扬",
    title: "曾洪扬：扎实推进宜居宜业和美乡村建设",
    link: "http://sc.people.com.cn/cpc/n2/2025/1104/c392659-41401068.html",
    year: "2025",
  },
  {
    id: "author-114",
    author: "曾洪扬",
    title: "曾洪扬：把改革动能转化为高质量发展效能",
    link: "http://sc.people.com.cn/cpc/n2/2025/0901/c392659-41339265.html",
    year: "2025",
  },
  {
    id: "author-115",
    author: "柳江",
    title: "启程！四川代表团赴京出席十四届全国人大四次会议",
    link: "https://scnews.newssc.org/system/20260303/001594432.html",
    year: "2026",
  },
  {
    id: "author-116",
    author: "唐安斌",
    title: "【对话深一度】全国人大代表唐安斌：全产业链发展人工智能需重视材料、人才强基",
    link: "https://scnews.newssc.org/system/20240308/001435876.html",
    year: "2024",
  },
  {
    id: "author-117",
    author: "唐安斌",
    title: "全国人大代表唐安斌：税惠助力，企业自主创新之路行稳致远",
    link: "http://sc.people.com.cn/n2/2023/0224/c379469-40314301.html",
    year: "2023",
  },
  {
    id: "author-118",
    author: "韩晓军",
    title: "韩晓军代表：建议加大国产化基础关键零部件推广应用支持力度",
    link: "http://sc.people.com.cn/n2/2025/0307/c345509-41156982.html",
    year: "2025",
  },
  {
    id: "author-119",
    author: "韩晓军",
    title: "全国人大代表韩晓军：加大力度支持高端装备制造企业高能级创新平台能力建设",
    link: "http://sc.people.com.cn/n2/2023/0309/c345167-40330908.html",
    year: "2023",
  },
  {
    id: "author-120",
    author: "韩晓军",
    title: "韩晓军代表：建议打造国家级高技能人才培训基地 支撑重大装备企业人才建设",
    link: "http://sc.people.com.cn/n2/2025/0307/c345509-41156973.html",
    year: "2025",
  },
  {
    id: "author-121",
    author: "韩晓军",
    title: "【新时代·奋斗者】韩晓军：奋进新时代，为全面建设社会主义现代化四川贡献在川央企力量",
    link: "https://scnews.newssc.org/system/20220529/001270975.html",
    year: "2022",
  },
  {
    id: "author-122",
    author: "高鹏凌",
    title: "让高速路成为革命老区振兴的“大动脉”|聚焦巴中两会⑱",
    link: "https://bazhong.scol.com.cn/jtlvx/202601/83194681.html",
    year: "2026",
  },
  {
    id: "author-123",
    author: "高鹏凌",
    title: "巴中文旅将以“六轮驱动”实现融合焕新|聚焦巴中两会⑯",
    link: "https://bazhong.scol.com.cn/jtlvx/202601/83194684.html",
    year: "2026",
  },
  {
    id: "author-124",
    author: "张永",
    title: "张永代表：加强基层卫生人才队伍建设",
    link: "http://sc.people.com.cn/n2/2024/0306/c345509-40767127.html",
    year: "2024",
  },
  {
    id: "author-125",
    author: "李君",
    title: "只此青绿 “蜀”你最美】全国人大代表李君：建设生态美丽宜居岫云村 推动乡村生态振兴",
    link: "https://scnews.newssc.org/system/20220303/001246027.html",
    year: "2022",
  },
  {
    id: "author-126",
    author: "李君",
    title: "【川网会客厅】全国人大代表李君：总书记让我好好干 乡村振兴需要更多年轻人",
    link: "https://scnews.newssc.org/system/20180304/000859324.html",
    year: "2018",
  },
  {
    id: "author-127",
    author: "李君",
    title: "李君：共同见证大模型和智能体的“群星闪耀”",
    link: "http://finance.people.com.cn/n1/2025/0619/c1004-40504375.html",
    year: "2025",
  },
  {
    id: "author-128",
    author: "李君",
    title: "李君代表：支持发展壮大农村集体经济",
    link: "http://sc.people.com.cn/n2/2024/0307/c345509-40768355.html",
    year: "2024",
  },
  {
    id: "author-129",
    author: "李君",
    title: "全国人大代表李君：深入实施大学生志愿服务西部计划",
    link: "http://sc.people.com.cn/n2/2023/0310/c345167-40332358.html",
    year: "2023",
  },
  {
    id: "author-130",
    author: "李玉梅",
    title: "李玉梅：建议将无创产前基因检测纳入医保报销范围",
    link: "http://cq.people.com.cn/n2/2026/0130/c365401-41488505.html",
    year: "2026",
  },
  {
    id: "author-131",
    author: "李玉梅",
    title: "全国人大代表李玉梅：税惠助民企发展 合规护行稳致远",
    link: "http://sc.people.com.cn/n2/2025/0301/c345167-41150766.html",
    year: "2025",
  },
  {
    id: "author-132",
    author: "李玉梅",
    title: "李玉梅：聚焦基层劳动者健康需求 关注一线工人待遇",
    link: "http://sc.people.com.cn/n2/2024/0304/c345167-40763810.html",
    year: "2024",
  },
  {
    id: "author-133",
    author: "李玉梅",
    title: "全国人大代表李玉梅：春风送来税惠暖",
    link: "http://sc.people.com.cn/n2/2023/0213/c345167-40299270.html",
    year: "2023",
  },
  {
    id: "author-134",
    author: "唐成凤",
    title: "全国人大代表唐成凤：税惠春风添动力 利民利企开新局",
    link: "http://sc.people.com.cn/n2/2025/0228/c345167-41150223.html",
    year: "2025",
  },
  {
    id: "author-135",
    author: "唐成凤",
    title: "全国人大代表唐成凤：税惠春风利企利民",
    link: "http://sc.people.com.cn/n2/2023/0304/c379469-40324603.html",
    year: "2023",
  },
  {
    id: "author-136",
    author: "王麒",
    title: "全国人大代表王麒：新能源汽车强势引领产业变革",
    link: "http://sc.people.com.cn/n2/2025/0228/c345167-41149748.html",
    year: "2025",
  },
  {
    id: "author-137",
    author: "王麒",
    title: "王麒代表：进一步加大依法保护民营企业产权力度 让民营企业没有后顾之忧",
    link: "http://sc.people.com.cn/n2/2025/0307/c345509-41156514.html",
    year: "2025",
  },
  {
    id: "author-138",
    author: "王麒",
    title: "全国人大代表王麒：建议制定出台公园城市建设国家标准",
    link: "http://sc.people.com.cn/n2/2024/0307/c345509-40767646.html",
    year: "2024",
  },
  {
    id: "author-139",
    author: "王麒",
    title: "全国人大代表王麒：建议支持高标准建设成渝综合性科学中心",
    link: "http://sc.people.com.cn/n2/2023/0307/c379469-40327852.html",
    year: "2023",
  },
  {
    id: "author-140",
    author: "余绍容",
    title: "全国人大代表余绍容：税惠滴灌“五星级”乡村振兴",
    link: "http://sc.people.com.cn/n2/2022/0303/c379469-35158434.html",
    year: "2022",
  },
  {
    id: "author-141",
    author: "余绍容",
    title: "全国人大代表余绍容：要带领村民借助各类新型实体企业发展特色产业",
    link: "http://finance.people.com.cn/n1/2022/0311/c1004-32372894.html",
    year: "2022",
  },
  {
    id: "author-142",
    author: "文绍牧",
    title: "文绍牧代表：高质量开展千亿立方米天然气生产基地建设",
    link: "http://lianghui.people.com.cn/2024/n1/2024/0310/c458609-40192580.html",
    year: "2024",
  },
  {
    id: "author-143",
    author: "胡晓玲",
    title: "全国人大代表胡晓玲：蝶变“黄连”话税收",
    link: "http://sc.people.com.cn/n2/2024/0306/c345167-40766627.html",
    year: "2024",
  },
  {
    id: "author-144",
    author: "胡晓玲",
    title: "全国人大代表胡晓玲：“春风”里黄连村尝出甜滋味",
    link: "http://sc.people.com.cn/n2/2023/0303/c345167-40323097.html",
    year: "2023",
  },
  {
    id: "author-145",
    author: "吉列子日",
    title: "吉列子日代表：让年轻人更快融入西部",
    link: "http://society.people.com.cn/n1/2025/0305/c1008-40430973.html",
    year: "2025",
  },
  {
    id: "author-146",
    author: "吉列子日",
    title: "吉列子日代表：实施凉山马铃薯产业集群项目助农增收",
    link: "http://lianghui.people.com.cn/2024/n1/2024/0310/c458609-40192581.html",
    year: "2024",
  },
  {
    id: "author-147",
    author: "吉列子日",
    title: "全国人大代表吉列子日：彝乡巨变感党恩",
    link: "http://sc.people.com.cn/n2/2023/0308/c345509-40328492.html",
    year: "2023",
  },
  {
    id: "author-148",
    author: "王永兰",
    title: "全国人大代表王永兰：三十年“田埂干部”的“路”愿与“梨”想 | 川网会客厅",
    link: "https://scnews.newssc.org/system/20260303/001594548.html",
    year: "2026",
  },
  {
    id: "author-149",
    author: "李树林",
    title: "全国人大代表李树林：履职8年 20余份建议都聚焦“三农”丨履职记",
    link: "https://scnews.newssc.org/system/20250302/001509860.html",
    year: "2025",
  },
  {
    id: "author-150",
    author: "李树林",
    title: "全国人大代表李树林：与“三农”共情 和税收共鸣",
    link: "https://finance.newssc.org/system/20250228/003574461.html",
    year: "2025",
  },
  {
    id: "author-151",
    author: "侯蓉",
    title: "侯蓉代表：保护好大熊猫栖息地 让它们永久生存和繁衍下去",
    link: "http://lianghui.people.com.cn/2023/n1/2023/0305/c452578-32637050.html",
    year: "2023",
  },
  {
    id: "author-152",
    author: "侯蓉",
    title: "代表通道丨侯蓉：不懈努力 恢复和保护大熊猫自然生存环境",
    link: "http://v.people.cn/n1/2023/0305/c452498-32636875.html",
    year: "2023",
  },
  {
    id: "author-153",
    author: "侯蓉",
    title: "十四届全国人大一次会议首场“代表通道”：侯蓉接受媒体采访",
    link: "http://lianghui.people.com.cn/2023/n1/2023/0305/c452579-32637024.html",
    year: "2023",
  },
  {
    id: "author-154",
    author: "董里",
    title: "董里代表：治水兴川 加快推进四川水利高质量发展",
    link: "http://finance.people.com.cn/n1/2025/0310/c1004-40435973.html",
    year: "2025",
  },
  {
    id: "author-155",
    author: "董里",
    title: "董里代表：大力推动嘉陵江流域水运发展",
    link: "http://lianghui.people.com.cn/2023/n1/2023/0313/c452473-32643535.html",
    year: "2023",
  },
  {
    id: "author-156",
    author: "董里",
    title: "董里代表：加快建设成渝地区能源安全保障基地",
    link: "http://finance.people.com.cn/n1/2024/0315/c1004-40196544.html",
    year: "2024",
  },
  {
    id: "author-157",
    author: "董里",
    title: "四川省水利厅厅长董里率队到巴中专题调研重点水利工程建设、防汛备汛等工作",
    link: "https://bz.newssc.org/system/20250612/003587766.html",
    year: "2025",
  },
  {
    id: "author-158",
    author: "董伟",
    title: "代表委员履职记丨全国人大代表董伟：为推动人口高质量发展鼓与呼",
    link: "https://scnews.newssc.org/system/20240303/001434180.html",
    year: "2024",
  },
  {
    id: "author-159",
    author: "董伟",
    title: "全国人大代表、西南医科大学科技处副处长董伟：回国搞科研，为祖国培养更多高精尖人才",
    link: "https://lz.newssc.org/system/20230301/003391879.html",
    year: "2023",
  },
  {
    id: "author-160",
    author: "董伟",
    title: "全国人大代表董伟：全国两会精神为泸州江阳医药发展添新动能",
    link: "http://sc.people.com.cn/n2/2024/0327/c379469-40790696.html",
    year: "2024",
  },
  {
    id: "author-161",
    author: "董伟",
    title: "全国人大代表董伟：为群众提供更好的医疗健康服务 希望支持泸州创建国家区域医药健康中心",
    link: "http://sc.people.com.cn/n2/2023/0303/c379470-40323798.html",
    year: "2023",
  },
  {
    id: "author-162",
    author: "刘政",
    title: "刘政到渠县调研城坝考古遗址公园项目",
    link: "https://dz.newssc.org/system/20211015/003208478.html",
    year: "2021",
  },
  {
    id: "author-163",
    author: "朱永繁",
    title: "全国人大代表朱永繁：税惠赋能建筑企业智能化、数字化、绿色化转型",
    link: "http://sc.people.com.cn/n2/2025/0228/c345167-41149747.html",
    year: "2025",
  },
  {
    id: "author-164",
    author: "朱永繁",
    title: "朱永繁代表：坚守央企担当 提升发展质量 坚决打好“十四五”规划收官战",
    link: "http://sc.people.com.cn/n2/2025/0306/c345167-41154967.html",
    year: "2025",
  },
  {
    id: "author-165",
    author: "朱永繁",
    title: "朱永繁代表：坚定不移推动高质量发展 为中国式现代化贡献央企力量",
    link: "http://sc.people.com.cn/n2/2024/0305/c345167-40765694.html",
    year: "2024",
  },
  {
    id: "author-166",
    author: "朱永繁",
    title: "全国人大代表朱永繁：融入战略大局 锻造硬核实力 推动高质量发展",
    link: "http://sc.people.com.cn/n2/2023/0304/c345509-40324461.html",
    year: "2023",
  },
  {
    id: "author-167",
    author: "余德春",
    title: "履职一年间 他们的意见建议有了回响",
    link: "https://scnews.newssc.org/system/20260304/001594657.html",
    year: "2026",
  },
  {
    id: "author-168",
    author: "江吉村",
    title: "全国人大代表江吉村：将藏药制剂分类纳入医保报销范围",
    link: "http://sc.people.com.cn/n2/2023/0309/c345509-40330588.html",
    year: "2023",
  },
  {
    id: "author-169",
    author: "江吉村",
    title: "全国人大代表江吉村：加强民族地区乡镇卫生院医疗服务能力建设",
    link: "http://sc.people.com.cn/n2/2023/0308/c407368-40329099.html",
    year: "2023",
  },
  {
    id: "author-170",
    author: "格西王母",
    title: "全国人大代表格西王姆：守望幸福“夕阳红”",
    link: "http://pic.people.com.cn/n1/2025/0227/c1016-40427524.html",
    year: "2025",
  },
  {
    id: "author-171",
    author: "黄河",
    title: "开局他们说丨黄河：以行动兑现承诺 用实干谱写新篇 为全省发展大局作出眉山新的贡献",
    link: "https://sichuan.scol.com.cn/ggxw/202602/83212096.html",
    year: "2026",
  },
  {
    id: "author-172",
    author: "严卫东",
    title: "开局他们说丨严卫东：继续舍得干、再上新台阶",
    link: "https://sichuan.scol.com.cn/ggxw/202602/83212046.html",
    year: "2026",
  },
  {
    id: "author-173",
    author: "严卫东",
    title: "严卫东：要学会“关起门来当书记”",
    link: "http://sc.people.com.cn/cpc/n2/2026/0303/c392659-41513701.html",
    year: "2026",
  },
  {
    id: "author-174",
    author: "严卫东",
    title: "严卫东：以能力提升带动工作提速",
    link: "http://sc.people.com.cn/cpc/n2/2025/1201/c392659-41428334.html",
    year: "2025",
  },
  {
    id: "author-175",
    author: "严卫东",
    title: "严卫东：尽量把“麻烦”留给党委政府",
    link: "http://sc.people.com.cn/cpc/n2/2025/0928/c392659-41366916.html",
    year: "2025",
  },
  {
    id: "author-176",
    author: "严卫东",
    title: "严卫东：让“遂宁是最好做生意的地方”得到更多企业家的认可",
    link: "http://sc.people.com.cn/cpc/n2/2025/1230/c392659-41458673.html",
    year: "2025",
  },
  {
    id: "author-177",
    author: "蒙媛",
    title: "蒙媛：以企业融入破题基层治理",
    link: "http://sc.people.com.cn/n2/2025/0305/c345167-41154545.html",
    year: "2025",
  },
  {
    id: "author-178",
    author: "蒙媛",
    title: "蒙媛：奔走新能源汽车“充电”前线 书写精彩履职答卷",
    link: "http://sc.people.com.cn/n2/2025/0305/c345167-41154534.html",
    year: "2025",
  },
  {
    id: "author-179",
    author: "蒙媛",
    title: "蒙媛代表：凝聚各方力量参与基层治理",
    link: "http://society.people.com.cn/n1/2025/0311/c1008-40436143.html",
    year: "2025",
  },
  {
    id: "author-180",
    author: "蒙媛",
    title: "蒙媛代表：推动智能网联新能源汽车产业川渝协同一体化发展",
    link: "http://sc.people.com.cn/n2/2025/0305/c345167-41154327.html",
    year: "2025",
  },
  {
    id: "author-181",
    author: "蒙媛",
    title: "蒙媛代表：完善企业参与基层治理的工作体系",
    link: "http://lianghui.people.com.cn/2024/n1/2024/0309/c458609-40192073.html",
    year: "2024",
  },
  {
    id: "author-182",
    author: "任敏",
    title: "全国人大代表任敏：小竹子编织乡村振兴大梦想",
    link: "http://sc.people.com.cn/n2/2025/0303/c379470-41152214.html",
    year: "2025",
  },
  {
    id: "author-183",
    author: "任敏",
    title: "两会好声音丨全国人大代表任敏：多措并举加强野生动物危害防控和致害补偿",
    link: "https://sichuan.scol.com.cn/ggxw/202503/82912116.html",
    year: "2025",
  },
  {
    id: "author-184",
    author: "任敏",
    title: "代表委员履职记丨全国人大代表任敏：助力百姓增收致富，小竹子做出乡村振兴大文章",
    link: "https://sichuan.scol.com.cn/ggxw/202503/82909779.html",
    year: "2025",
  },
  {
    id: "author-185",
    author: "任敏",
    title: "代表委员返乡记⑤丨任敏：做大竹林经济，让更多村民在家门口安居乐业",
    link: "https://sichuan.scol.com.cn/xwtg/202403/82487513.html",
    year: "2024",
  },
  {
    id: "author-186",
    author: "施小琳",
    title: "施小琳在调研企业服务平台推进情况并召开座谈会时强调：提升服务平台能级质效、赋能企业高质量发展，为科技创新和现代产业发展向新向优注入持续动能",
    link: "https://scnews.newssc.org/system/20260224/001593005.html",
    year: "2026",
  },
  {
    id: "author-187",
    author: "汪其德",
    title: "全国人大代表汪其德：写好南江黄羊这篇“土”文章",
    link: "https://scnews.newssc.org/system/20260228/001593809.html",
    year: "2026",
  },
  {
    id: "author-188",
    author: "汪其德",
    title: "全国人大代表汪其德建议：加大全国革命老区重点城市巴中石油天然气勘探开发力度",
    link: "https://bz.newssc.org/system/20250310/003575810.html",
    year: "2025",
  },
  {
    id: "author-189",
    author: "汪其德",
    title: "全国人大代表汪其德建议：加大农村义务教育小规模学校投入",
    link: "https://bz.newssc.org/system/20250310/003575807.html",
    year: "2025",
  },
  {
    id: "author-190",
    author: "新甲旦真",
    title: "新甲旦真：加强对少数民族古籍的保护",
    link: "https://scnews.newssc.org/system/20230306/001346546.html",
    year: "2023",
  },
  {
    id: "author-191",
    author: "新甲旦真",
    title: "【只此青绿 “蜀”你最美】全国人大代表新甲旦真：全民参与 共护黄河出川清水向东流",
    link: "https://scnews.newssc.org/system/20220307/001247175.html",
    year: "2022",
  },
  {
    id: "author-192",
    author: "许强",
    title: "许强荣获何梁何利基金“科学与技术进步奖”",
    link: "http://sc.people.com.cn/n2/2026/0203/c345167-41491997.html",
    year: "2026",
  },
  {
    id: "author-193",
    author: "许强",
    title: "许强：打破壁垒 培养青年拔尖创新人才",
    link: "http://edu.people.com.cn/n1/2025/0106/c367001-40396348.html",
    year: "2025",
  },
  {
    id: "author-194",
    author: "许强",
    title: "许强：让高校真正成为科技成果转化的策源地",
    link: "http://edu.people.com.cn/n1/2025/0115/c1006-40402646.html",
    year: "2025",
  },
  {
    id: "author-195",
    author: "许强",
    title: "许强代表：建议加强地震高风险地区房屋抗震改造",
    link: "http://sc.people.com.cn/n2/2025/0306/c345509-41155910.html",
    year: "2025",
  },
  {
    id: "author-196",
    author: "许强",
    title: "许强代表：探索人工智能教育新模式 培养定义未来的人",
    link: "http://sc.people.com.cn/n2/2025/0310/c345167-41159042.html",
    year: "2025",
  },
  {
    id: "author-197",
    author: "晏鲁作",
    title: "2020我的扶贫故事．凉山．晏鲁作：寻找致富路 脱贫勇争先",
    link: "https://ls.newssc.org/system/20200922/003004472.html",
    year: "2020",
  },
  {
    id: "author-198",
    author: "晏鲁作",
    title: "两会好声音丨全国人大代表晏鲁作：让“凉山桑蚕茧”品牌走向更大舞台",
    link: "https://liangshan.scol.com.cn/sdxw/202503/82915119.html",
    year: "2025",
  },
  {
    id: "author-199",
    author: "晏鲁作",
    title: "代表委员返乡记⑧丨晏鲁作：努力推动优质宁南茧丝走向世界",
    link: "https://liangshan.scol.com.cn/sdxw/202403/82489676.html",
    year: "2024",
  },
  {
    id: "author-200",
    author: "王瑛",
    title: "王瑛代表：建议川渝高竹新区加快构建区域法治一体化",
    link: "http://sc.people.com.cn/n2/2025/0310/c345167-41158948.html",
    year: "2025",
  },
  {
    id: "author-201",
    author: "王瑛",
    title: "央媒看四川 | 全国人大代表、四川省广安市副市长王瑛：加快促进农村地区医养融合发展",
    link: "https://sichuan.scol.com.cn/tfrm/202503/82914837.html",
    year: "2025",
  },
  {
    id: "author-202",
    author: "王瑛",
    title: "【酒城巾帼榜】王瑛: 一个科研团队的“定海神针”",
    link: "https://local.newssc.org/system/20210307/003092363.htm",
    year: "2021",
  },
  {
    id: "author-203",
    author: "张祖涛",
    title: "央媒看四川 | 全国人大代表、成都工业学院副校长张祖涛：建设高水平地方应用型高校",
    link: "https://sichuan.scol.com.cn/tfrm/202503/82914840.html",
    year: "2025",
  },
  {
    id: "author-204",
    author: "严宝玉",
    title: "严宝玉代表：聚焦金融“五篇大文章” 支持实体经济发展",
    link: "http://sc.people.com.cn/n2/2025/0306/c345509-41155553.html",
    year: "2025",
  },
  {
    id: "author-205",
    author: "严宝玉",
    title: "严宝玉代表：为奋力谱写中国式现代化四川新篇章提供高质量金融服务",
    link: "http://sc.people.com.cn/n2/2024/0307/c345167-40767569.html",
    year: "2024",
  },
  {
    id: "author-206",
    author: "严宝玉",
    title: "两会好声音丨全国人大代表严宝玉：对症下药，破解中小微企业融资痛点、堵点",
    link: "https://sichuan.scol.com.cn/ggxw/202303/58828849.html",
    year: "2023",
  },
  {
    id: "author-207",
    author: "严宝玉",
    title: "川观金融智库·对话大咖丨人民银行四川省分行行长严宝玉：推动金融高质量发展 奋力谱写中国式现代化四川新篇章",
    link: "https://sichuan.scol.com.cn/ggxw/202401/82452816.html",
    year: "2024",
  },
  {
    id: "author-208",
    author: "欧阳梅",
    title: "两会好声音丨全国人大代表欧阳梅：建议支持汉巴南铁路巴中至汉中段纳入国家“十五五”规划重点建设项目",
    link: "https://bazhong.scol.com.cn/jtlvx/202503/82915604.html",
    year: "2025",
  },
  {
    id: "author-209",
    author: "吴忠跃",
    title: "两会好声音丨全国人大代表吴忠跃：建设中国发动机博物馆 开展航空发动机科普教育",
    link: "https://sichuan.scol.com.cn/ggxw/202303/58829417.html",
    year: "2023",
  },
  {
    id: "author-210",
    author: "刘廷安",
    title: "刘廷安、李杰当选资阳市人大常委会副主任",
    link: "https://sichuan.scol.com.cn/xwtg/202501/82876516.html",
    year: "2025",
  },
  {
    id: "author-211",
    author: "钟波",
    title: "全国人大代表钟波：税务部门行政审批制度改革，让企业感受到营商环境优化的切实成果",
    link: "http://sc.people.com.cn/n2/2025/0302/c379469-41151175.html",
    year: "2025",
  },
  {
    id: "author-212",
    author: "钟波",
    title: "全国人大代表钟波：建议制定并发布家用智能投影机强制性国家标准",
    link: "http://sc.people.com.cn/n2/2023/0307/c345167-40327654.html",
    year: "2023",
  },
  {
    id: "author-213",
    author: "杨兴平",
    title: "杨兴平：扎实细致做好世运会筹备冲刺阶段工作",
    link: "http://sc.people.com.cn/n2/2025/0801/c379470-41309273.html",
    year: "2025",
  },
  {
    id: "author-214",
    author: "杨兴平",
    title: "杨兴平赴泸州市古蔺县调研“致泸合作·乡村振兴示范共建工程”推进情况",
    link: "https://scnews.newssc.org/system/20251029/001566091.html",
    year: "2025",
  },
  {
    id: "author-215",
    author: "甘华田",
    title: "两会好声音丨全国政协委员甘华田：摒弃学历歧视，创造更加公平就业环境",
    link: "https://sichuan.scol.com.cn/ggxw/202503/82914815.html",
    year: "2025",
  },
  {
    id: "author-216",
    author: "甘华田",
    title: "C视频丨全国政协委员甘华田：建议将“学历歧视”纳入就业歧视范畴",
    link: "https://sichuan.scol.com.cn/spsc/202503/82910631.html",
    year: "2025",
  },
  {
    id: "author-217",
    author: "甘华田",
    title: "代表委员履职记丨全国政协委员甘华田：让家庭医生“真正”走进千家万户",
    link: "https://sichuan.scol.com.cn/ggxw/202502/82903421.html",
    year: "2025",
  },
  {
    id: "author-218",
    author: "甘华田",
    title: "两会好声音丨全国政协委员甘华田：老年人不只需要文娱保健，老龄教育质量有待提高",
    link: "https://sichuan.scol.com.cn/ggxw/202403/82478480.html",
    year: "2024",
  },
  {
    id: "author-219",
    author: "甘华田",
    title: "两会好声音丨全国政协委员甘华田：多措并举打击养老诈骗",
    link: "https://sichuan.scol.com.cn/ggxw/202303/58825761.html",
    year: "2023",
  },
  {
    id: "author-220",
    author: "彭映梅",
    title: "彭映梅代表：锚定高质量发展首要任务 奋力推进中国式现代化雅安实践",
    link: "http://sc.people.com.cn/n2/2025/0304/c345167-41152958.html",
    year: "2025",
  },
  {
    id: "author-221",
    author: "彭映梅",
    title: "彭映梅代表：高水平建设世界大熊猫文化旅游重要目的地",
    link: "http://sc.people.com.cn/n2/2024/0306/c345509-40766335.html",
    year: "2024",
  },
  {
    id: "author-222",
    author: "彭映梅",
    title: "全国人大代表彭映梅：建设川藏经济协作试验区和世界大熊猫文化旅游重要目的地",
    link: "http://sc.people.com.cn/n2/2023/0306/c345509-40326153.html",
    year: "2023",
  },
  {
    id: "author-223",
    author: "彭映梅",
    title: "全国人大代表彭映梅：雅安高质量发展新步伐 生态优先、绿色发展",
    link: "https://scnews.newssc.org/system/20230310/001347635.html",
    year: "2023",
  },
  {
    id: "author-224",
    author: "余绍容",
    title: "代表委员返乡记丨余绍容： 把全国“两会精神”带回羌乡，打开乡村振兴新思路",
    link: "https://sichuan.scol.com.cn/tfrm/202403/82488134.html",
    year: "2024",
  },
  {
    id: "author-225",
    author: "余绍容",
    title: "两会好声音丨全国人大代表余绍容：多措并举加大改造山区农村公路",
    link: "https://sichuan.scol.com.cn/ggxw/202403/82480968.html",
    year: "2024",
  },
  {
    id: "author-226",
    author: "余绍容",
    title: "全国人大代表余绍容：税惠滴灌“五星级”乡村振兴",
    link: "http://sc.people.com.cn/n2/2022/0303/c379469-35158434.html",
    year: "2022",
  },
  {
    id: "author-227",
    author: "余绍容",
    title: "全国人大代表余绍容：要带领村民借助各类新型实体企业发展特色产业",
    link: "http://finance.people.com.cn/n1/2022/0311/c1004-32372894.html",
    year: "2022",
  },
  {
    id: "author-228",
    author: "余绍容",
    title: "带着期盼上两会③余绍容：铺就“四好”农村路 打通乡村振兴“快车道”",
    link: "https://sichuan.scol.com.cn/tfrm/202403/82478113.html",
    year: "2024",
  },
  {
    id: "author-229",
    author: "王树明",
    title: "全国人大代表王树明：守护好“一老一小” 阿坝州托起稳稳的幸福｜两会最前线",
    link: "https://scnews.newssc.org/system/20250308/001511255.html",
    year: "2025",
  },
  {
    id: "author-230",
    author: "王树明",
    title: "我从防灾减灾一线来丨王树明代表：坚持预防为主，为人民群众构建生命财产安全网",
    link: "https://sichuan.scol.com.cn/ggxw/202303/58827182.html",
    year: "2023",
  },
  {
    id: "author-231",
    author: "罗先刚",
    title: "罗先刚：坚定科技战略的定力",
    link: "http://kpzg.people.com.cn/n1/2024/0822/c404214-40304013.html",
    year: "2024",
  },
  {
    id: "author-232",
    author: "曾道群",
    title: "代表委员返乡记⑥丨曾道群：发展“高滩”特色产业，走好生态绿色农旅融合之路",
    link: "https://sichuan.scol.com.cn/ggxw/202403/82487416.html",
    year: "2024",
  },
  {
    id: "author-233",
    author: "曾道群",
    title: "全国人大代表曾道群：“以民声定民生” 她是盛开在乡村的向阳花",
    link: "http://sc.people.com.cn/n2/2024/0301/c345458-40761738.html",
    year: "2024",
  },
  {
    id: "author-234",
    author: "曾道群",
    title: "全国人大代表曾道群：只有与群众同坐一条板凳，才能听到真声音",
    link: "http://sc.people.com.cn/n2/2025/0304/c379470-41152522.html",
    year: "2025",
  },
  {
    id: "author-235",
    author: "赵波",
    title: "赵波：厚植爱党、爱国、爱社会主义的情感",
    link: "http://sc.people.com.cn/cpc/n2/2026/0130/c392659-41488650.html",
    year: "2026",
  },
  {
    id: "author-236",
    author: "赵波",
    title: "赵波：加快打造绿色化工千亿级产业集群",
    link: "http://sc.people.com.cn/cpc/n2/2025/1202/c392659-41429886.html",
    year: "2025",
  },
  {
    id: "author-237",
    author: "赵波",
    title: "赵波：全力以赴补短强弱，坚决冲刺全年目标",
    link: "http://sc.people.com.cn/cpc/n2/2025/1104/c392659-41400975.html",
    year: "2025",
  },
  {
    id: "author-238",
    author: "赵波",
    title: "赵波：全州各族各界人士要拿出马不停蹄的干劲",
    link: "http://sc.people.com.cn/cpc/n2/2026/0303/c392659-41513692.html",
    year: "2026",
  },
  {
    id: "author-239",
    author: "赵波",
    title: "赵波：做大做强优势产业，持续提升核心竞争力",
    link: "http://sc.people.com.cn/cpc/n2/2025/0801/c392659-41309953.html",
    year: "2025",
  },
  {
    id: "author-240",
    author: "王麟",
    title: "王麟为四川省教育系统依法治校能力提升培训班讲授法治课",
    link: "http://sc.people.com.cn/n2/2025/0821/c345167-41329223.html",
    year: "2025",
  },
]
