export const topicYearTabs = ['2025', '2024', '2023']
export const topicSphereList = [
  { key: 'livelihood', label: '民生', size: 'sm', num: 229 },
  { key: 'four', label: '四个发力', size: 'xl', num: 236 },
  { key: 'law', label: '法治四川', size: 'md', num: 75 },
  { key: 'plan', label: '发展规划', size: 'md', num: 82 },
  { key: 'safety', label: '安全发展', size: 'sm', num: 6 },
  { key: 'traffic', label: '交通', size: 'lg', num: 57 },
  { key: 'chengyu', label: '成渝地区双城经济圈', size: 'wide', num: 61 },
  { key: 'finance', label: '财税金融', size: 'lg', num: 38 },
  { key: 'ecology', label: '生态', size: 'lg', num: 8 },
  { key: 'culture', label: '文化旅游', size: 'xl', num: 52 },
  { key: 'industry', label: '新质生产力', size: 'md', num: 6 },
  { key: 'reform', label: '改革开放', size: 'lg', num: 41 },
  { key: 'grain', label: '天府粮仓', size: 'sm', num: 25 },
  { key: 'integration', label: '城乡融合', size: 'md', num: 5 },
  { key: 'other', label: '其他', size: 'sm', num: 55 },
]
export const topicListByYear = {
  2025: [
    {
      id: '25-liv-01',
      title: '关于学前教育教师享受中小学教师同等待遇的建议',
      author: '王永兰',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-02',
      title: '关于适当放宽幼升小年龄范围的建议',
      author: '魏琴',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-03',
      title: '关于加强普通高中职业生涯规划教育的建议',
      author: '欧阳梅',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-04',
      title: '关于“双一流”扩容增设区域急需赛道的建议',
      author: '尚丽平',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-05',
      title: '关于加强国产工业软件人才培养的建议',
      author: '张祖涛',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-06',
      title: '关于进一步推进地方高水平应用型高校建设的建议',
      author: '张祖涛',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-07',
      title: '关于进一步提高全日制博士研究生奖助学金的建议',
      author: '张祖涛',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-08',
      title: '关于普及人工智能教育培养拔尖创新人才的建议',
      author: '苟兴龙',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-09',
      title: '关于将落下闳的科研精神和贡献编入全国统编教材的建议',
      author: '李君',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-10',
      title: '关于在青少年学生群体中加强人民代表大会制度教育的建议',
      author: '罗春梅',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-11',
      title: '关于在青少年学生群体中加强人民代表大会制度教育的建议',
      author: '罗春梅',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-12',
      title: '关于加强新时代伟大变革成功案例和红色文化资源融入思想政治教育的建议',
      author: '苟兴龙',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-13',
      title: '关于将革命老区省属应用型本科高校纳入国家支持计划的建议',
      author: '苟兴龙',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-14',
      title: '关于扩大国家银龄教师行动计划实施范围和规模的建议',
      author: '苟兴龙',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-15',
      title: '关于加强国家实验室战略人才力量及其后备队伍建设的建议',
      author: '吴忠跃',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-16',
      title: '改革我国高校专利激励政策 切实规避投机行为提高质量与转化率',
      author: '里赞',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-17',
      title: '优化我国高校科研人员出境持用证件政策 切实促进对外学术交流合作',
      author: '里赞',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-18',
      title: '关于进一步加强民生建设筑牢普惠性基础性兜底性保障的建议',
      author: '吉列子日',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-19',
      title: '关于积极应对农村人口老龄化 加快完善我国农村养老服务体系建设',
      author: '里赞',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-20',
      title: '关于加快建立我国公共监护人制度的建议',
      author: '里赞',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-21',
      title: '关于支持革命老区提升就业公共服务水平的建议',
      author: '胡晓玲',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-22',
      title: '关于加大对革命老区就业创业补助资金转移支付力度的建议',
      author: '李君',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-23',
      title: '关于坚决纠正就业领域年龄歧视的建议',
      author: '郑功成',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-24',
      title: '关于大学生不愿意就业与缓就业的调研及相关的建议',
      author: '张祖涛',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-25',
      title: '关于高度重视解决国有企业、事业单位社会招聘中学校、学历歧视的建议',
      author: '刘廷安',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-26',
      title: '关于消除就业和晋升领域第一学历歧视的建议',
      author: '',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-27',
      title: '关于优化我国无障碍设施建设与管理的建议',
      author: '钟波',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-28',
      title: '关于支持建筑业高质量发展的建议',
      author: '郑望春',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-29',
      title: '关于加快建立住宅保险制度的建议',
      author: '郑功成',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-30',
      title: '关于加快促进农村地区医养结合发展的建议',
      author: '杨兴平',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-31',
      title: '关于强化食品安全监管体系建设筑牢“从农田到餐桌”全链条防线的建议',
      author: '吉列子日',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-32',
      title: '关于支持欠发达地区拓展城镇开发空间的建议（延伸）',
      author: '',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-33',
      title: '关于优化国土空间规模使用要求的建议',
      author: '苟兴龙',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-liv-34',
      title: '关于聚焦家庭医生和社区养老，让家庭医生真正走进千家万户的建议',
      author: '甘华田',
      link: '',
      topicKey: 'livelihood',
    },
    {
      id: '25-eco-01',
      title: '关于优化空气质量考评体系实现环境经济和社会效益共赢的建议',
      author: '尚丽平',
      link: '',
      topicKey: 'ecology',
    },
    {
      id: '25-eco-02',
      title: '关于进一步加强山洪地质灾害避险搬迁政策支持的建议',
      author: '彭映梅',
      link: '',
      topicKey: 'ecology',
    },
    {
      id: '25-eco-03',
      title: '关于加强野生动物致害补偿工作的建议',
      author: '余绍容',
      link: '',
      topicKey: 'ecology',
    },
    {
      id: '25-eco-04',
      title: '关于有效保护好野生动物，避免对农民群众生产生活造成严重影响的建议',
      author: '郑望春',
      link: '',
      topicKey: 'ecology',
    },
    {
      id: '25-eco-05',
      title: '关于加强西部山区生态环境宣传保护推动全民协同参与生态环境保护的建议',
      author: '郑望春',
      link: '',
      topicKey: 'ecology',
    },
    {
      id: '25-eco-06',
      title: '关于调整矿山地质环境保护与土地复垦方案编制审批流程的建议',
      author: '郑望春',
      link: '',
      topicKey: 'ecology',
    },
    {
      id: '25-eco-07',
      title: '关于加强野生动物危害防控和致害补偿的建议',
      author: '',
      link: '',
      topicKey: 'ecology',
    },
    {
      id: '25-eco-08',
      title: '关于有效保护好野生动物 避免对农民群众生产生活造成严重影响的建议',
      author: '',
      link: '',
      topicKey: 'ecology',
    },
    {
      id: '25-cul-01',
      title: '关于大力传承弘扬三苏文化东坡文化深化家庭家教家风建设的建议',
      author: '黄河',
      link: '',
      topicKey: 'culture',
    },
    {
      id: '25-cul-02',
      title: '关于支持达州市联动周边打造大巴山国际旅游度假区的建议',
      author: '胡晓玲',
      link: '',
      topicKey: 'culture',
    },
    {
      id: '25-cul-03',
      title: '关于支持九寨沟景区湖群沼泽化治理的建议',
      author: '王树明',
      link: '',
      topicKey: 'culture',
    },
    {
      id: '25-cul-04',
      title: '关于推进大熊猫入住“蜀南竹海”的建议',
      author: '魏琴',
      link: '',
      topicKey: 'culture',
    },
    {
      id: '25-cul-05',
      title: '关于大力推进文化产品出海的建议',
      author: '杨兴平',
      link: '',
      topicKey: 'culture',
    },
    {
      id: '25-ind-01',
      title: '关于加强科技赋能、将薯业纳入国家农业新质生产力战略布局的建议',
      author: '魏彦玉',
      link: '',
      topicKey: 'industry',
    },
    {
      id: '25-ind-02',
      title: '关于在四川打造“光经济”新质生产力战略高地的建议',
      author: '罗先刚',
      link: '',
      topicKey: 'industry',
    },
  ],
  2024: [
    {
      id: '24-four-001',
      title: '关于支持在四川宜宾建立国家全固态电池创新中心的建议',
      author: '廖文彬',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-002',
      title: '关于支持四川先行先试在重点领域进行紧缺人才自主培养机制创新的建议',
      author: '罗先刚',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-003',
      title: '关于支持在川布局建设综合类、中医类国家医学中心的建议',
      author: '全团',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-004',
      title: '关于支持四川建设国家工业云制造创新中心的建议',
      author: '全团',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-005',
      title:
        '关于加快推进钒钛资源综合开发利用科技攻关和钒钛资源综合利用国家重点实验室优化重组的建议',
      author: '全团',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-006',
      title: '关于在专利法中增加国家使用权的建议',
      author: '尚丽平',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-007',
      title: '关于发挥国企产业链链长作用，培植核心领域产业联盟，打造中国式技术标准和输出能力的建议',
      author: '李慧',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-008',
      title: '建立有关国家实验室法律配套基础制度的建议',
      author: '吴忠跃',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-009',
      title: '关于国家实验室硕博士授予权的建议',
      author: '吴忠跃',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-010',
      title: '关于设立国家西部人才基金的建议',
      author: '尧德中',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-011',
      title: '关于支持钒钛资源综合利用国家重点实验室优化重组的建议',
      author: '邹明',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-012',
      title: '关于支持构建西部矿产品（钒钛钢铁）骨干流通走廊的建议',
      author: '邹明',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-013',
      title: '关于支持加强名优白酒知识产权保护的建议',
      author: '曾从钦',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-014',
      title: '关于尽快建立动物新品种权保护体系的建议',
      author: '杨武云',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-015',
      title: '关于严厉打击知识产权恶意诉讼 规范权利行使的建议',
      author: '钟波',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-016',
      title: '关于推进农村地区网络覆盖的建议',
      author: '郑望春',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-017',
      title: '关于支持中小型燃气轮机现代产业链建设的建议',
      author: '曹天兰',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-018',
      title: '关于加快制造业“智改数转”，高质量建设成渝地区高端装备产业集群的建议',
      author: '曹天兰',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-019',
      title: '关于支持四川晶硅光伏产业发展的建议案',
      author: '陈光浩',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-020',
      title: '关于支持四川建设航空航天装备先进制造业集群的建议',
      author: '陈张铭',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-021',
      title: '关于支持自贡建设氢能装备制造和应用基地的建议',
      author: '陈张铭',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-022',
      title: '关于支持四川创建国家新型工业化示范区加快打造国家战略腹地的建议',
      author: '翟刚',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-023',
      title: '关于支持四川省建设全球稀土资源综合利用基地的建议',
      author: '翟刚',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-024',
      title: '关于支持达州建设热电联产循环经济园的建议',
      author: '苟兴龙',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-025',
      title: '关于依托标志性产品链主企业，在宜宾建设全国近零碳园区的建议',
      author: '廖文彬',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-026',
      title: '关于进一步加快我国多种储能建设推进低碳中国进程的建议',
      author: '刘汉元',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-027',
      title: '关于加快工业互联网平台产业发展的建议',
      author: '柳江代表',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-028',
      title: '关于大力推进县域工业数字化转型，助力打造新质生产力的建议',
      author: '马奎',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-029',
      title: '关于支持雅安开展算力电力协同试点的建议',
      author: '彭映梅',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-030',
      title: '关于支持四川探索试点碳足迹管理先行先试建设动力电池产业绿色零碳示范区的建议',
      author: '全团',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-031',
      title: '关于支持成都纳入国家数据基础设施区域性节点布局的建议',
      author: '全团',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-032',
      title: '支持四川省自贡市创建国家新型工业化示范区',
      author: '李慧建议3',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-033',
      title: '关于“加强丝纺行业科研 助力行业数字化转型”的建议',
      author: '王丽',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-034',
      title: '关于落实绿电交易政策进一步支持水电清洁能源纳入绿电范围的建议',
      author: '庹庆明',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-035',
      title: '关于加快四川民族地区交通建设和清洁能源开发的建议',
      author: '何延政',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-036',
      title: '关于建立电网碳排放因子数据库 完善绿色电力交易机制的建议',
      author: '刘汉元',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-037',
      title: '关于支持清洁能源开发和电力通道建设的建议',
      author: '罗振华',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-038',
      title: '关于进一步健全完善氢能管理制度体系的建议',
      author: '吴群刚',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-039',
      title: '关于在川布局建设国家清洁能源',
      author: '吴群刚',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-040',
      title: '关于支持西部清洁能源省份加强钒钛、晶硅光伏等绿色载能产业发展的建议',
      author: '邹明',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-041',
      title: '关于推动低空经济加快发展的建议',
      author: '陈张铭',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-042',
      title: '关于健全无人机安全管理法律体系 促进低空经济安全有序发展的建议',
      author: '刘传健',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-043',
      title: '关于大力发展低空经济加快构建新应用场景的建议',
      author: '曾洪扬',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-044',
      title: '关于支持在四川打造商业航天产业基地的建议',
      author: '翟刚',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-045',
      title: '关于促进大模型产业生态链建设，推进产业化应用落地的建议',
      author: '柳江',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-046',
      title: '（柳江代表）关于促进家庭服务机器人产业应用落地的建议',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-047',
      title: '关于紧抓“AI+算力”机遇，加大对西南地区智算产业发展支持的建议',
      author: '马奎',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-048',
      title: '围绕人工智能为代表的新质生产力发展强基固本建议',
      author: '唐安斌',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-049',
      title: '关于在四川布局建设航空领域高能级创新平台和国家战略性新兴产业集群的建议',
      author: '韩晓军',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-050',
      title: '关于支持在四川打造大飞机综合性产业备份基地的建议',
      author: '韩晓军',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-051',
      title: '关于将成都航空枢纽定位为全方位门户复合型国际航空枢纽的建议',
      author: '黄强',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-052',
      title: '关于加快创新型人才培养 提升中国民航国际竞争力的建议',
      author: '刘传健',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-053',
      title: '关于加快修订出台《中华人民共和国民用航空法》的建议',
      author: '刘传建',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-054',
      title: '关于加强中医药行业知识产权保护的几点建议',
      author: '耿福能',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-055',
      title: '关于中医药走出海外 国际化发展的建议',
      author: '耿福能',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-056',
      title: '关于以野生珍贵、濒危动物为来源的中药管理建议',
      author: '耿福能',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-057',
      title: '关于办理涉及以野生珍贵、濒危动物为来源的中药案件的建议',
      author: '耿福能',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-058',
      title: '关于中医数字化推进健康网格化服务全民体系建设的建议',
      author: '耿福能',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-059',
      title: '关于支持全国革命老区重点城市巴中中医药产业高质量发展的建议',
      author: '高鹏凌',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-060',
      title: '关于加快推进将天冬纳入食药物质目录管理的建议',
      author: '张永',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-061',
      title: '关于规范网络经济、鼓励支持实体经济，发展新质生产力的建议',
      author: '耿福能',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-062',
      title: '关于集聚创新和资源要素推动地方国企发展新质生产力的建议',
      author: '王诚',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-063',
      title: '关于整治“网红”乱象构建和谐网络经济生态的建议',
      author: '耿福能',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-064',
      title: '关于加强网络治理的建议',
      author: '李君',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-065',
      title:
        '关于规范和限制电商行业，防止其野蛮生长，消灭就业岗位，促进社会稳定、国家安全和经济健康发展的建议',
      author: '李玉梅',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-066',
      title: '关于营造健康网络空间的建议',
      author: '唐成凤',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-067',
      title: '关于规范美团、大众点评等平台费用收取及加强食品安全监管的建议',
      author: '王丽',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-068',
      title: '关于进一步保障维护网络安全的建议',
      author: '王麒',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-069',
      title: '关于加强数字乡村建设的建议',
      author: '余绍容',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-070',
      title: '关于积极推进数字化技术应用于民生保障事业的建议',
      author: '郑功成',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-071',
      title: '关于打造我国西南地区CCUS产业中心的建议',
      author: '文绍牧',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-072',
      title: '关于高质量开展四川盆地千亿立方米天然气生产基地建设的建议',
      author: '文绍牧',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-073',
      title: '关于加大页岩油气资源勘探开发和增储上产力度的建议',
      author: '文绍牧',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-074',
      title: '关于加快完善我国能源应急保障体系建设的建议',
      author: '文绍牧',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-075',
      title: '关于完善《矿产资源法》保障国家油气能源安全的建议',
      author: '文绍牧',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-076',
      title: '关于实施页岩气资源地优惠政策的建议（联合建议）',
      author: '余先河',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-077',
      title: '关于支持渠县现代粮油园区创建国家级现代农业产业园区的建议',
      author: '胡晓玲',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-078',
      title: '关于调整山区农业发展保障结构，确保传统优势产业可持续发展的建议',
      author: '胡晓玲',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-079',
      title: '关于支持四川省凉山彝族自治州创建国家马铃薯产业集群的建议',
      author: '吉列子日',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-080',
      title: '关于协同推动粮经烟融合发展的建议',
      author: '李君',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-081',
      title: '关于规范家禽屠宰行业准入标准 助力行业有序健康发展的建议',
      author: '刘汉元',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-082',
      title: '关于推动明月山绿色发展示范带竹产业高质量发展的建议',
      author: '吕祖艳',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-083',
      title: '关于支持川东北地区发展农产品精深加工的建议',
      author: '欧阳梅',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-084',
      title: '关于加强适合中高山区农机设备研发和推广的建议',
      author: '彭映梅',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-085',
      title: '关于支持米易县国家现代农业产业园创建的建议',
      author: '王永兰',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-086',
      title: '关于加快启动建立区域农业新质生产力集中示范片的建议',
      author: '吴德',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-087',
      title: '关于在川布局建设国家农业高新技术',
      author: '吴群刚',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-088',
      title: '关于持续加大对国家农高区创建工作支持力度的建议',
      author: '余绍容',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-089',
      title: '关于持续加强少数民族地区、欠发达地区基础设施建设让农民共同富裕乡村全面振兴发展的建议',
      author: '郑望春',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-090',
      title: '关于持续加强“宜居、宜业和美乡村”建设”需求的建议',
      author: '郑望春',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-091',
      title: '关于以科技创新为引擎培育“三农”新质生产力，全面推进乡村振兴的建议',
      author: '耿福能',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-092',
      title: '关于设立乡村污水处理专项资金的建议',
      author: '曾娜',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-093',
      title: '关于加大对通川区建设“国家乡村振兴示范县”支持力度的建议',
      author: '胡晓玲',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-094',
      title: '关于交通建设支持政策多向乡村振兴重点帮扶地区倾斜的建议',
      author: '吉列子日',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-095',
      title: '关于加大扶持农村集体经济发展的建议',
      author: '李君',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-096',
      title: '关于加大农村生活垃圾处理力度的建议',
      author: '李君',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-097',
      title: '关于保障农村建设用地和设施用地的建议',
      author: '李君',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-098',
      title: '关于城乡融合以工引农以农助农促发展的建议',
      author: '李树林',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-099',
      title: '关于做大做强“强村公司”推进乡村全面振兴的建议',
      author: '杨心平',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-100',
      title: '关于持续支持大熊猫国家公园建设的建议',
      author: '庹庆明',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-101',
      title: '关于加快将世界自然遗产保护整合到国家公园并勘界立标的建议',
      author: '庹庆明',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-102',
      title: '关于进一步加强凉山山系大熊猫保护的建议',
      author: '侯蓉',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-103',
      title: '关于支持四川省雅安市宝兴县纳入国家生态综合补偿试点县的建议',
      author: '庹庆明',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-104',
      title: '关于在美丽城市建设中给予四川省广元市倾斜支持的建议',
      author: '董里',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-105',
      title: '关于减少燃放烟花爆竹带来大气污染的建议',
      author: '董伟',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-106',
      title: '关于推动城镇污水治理两年攻坚行动的建议',
      author: '苟兴龙',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-107',
      title: '关于全面推行生态系统生产总值（GEP）核算并建立发布机制的建议',
      author: '梁伟',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-108',
      title: '关于加快推动医疗机构污水新污染物治理能力提升的建议',
      author: '刘政',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-109',
      title: '关于进一步推动可再生能源健康可持续发展的建议',
      author: '朱永繁',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-110',
      title: '关于支持四川省打造美丽中国先行区的建议',
      author: '全团',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-111',
      title: '关于简化我国氦气回收利用程序的建议',
      author: '李慧',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-112',
      title: '关于支持万源生态功能区产业准入负面清单优化调整的建议',
      author: '文绍牧',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-113',
      title: '关于支持四川大渡河丹巴水电站环评送审工作建议',
      author: '余德春',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-114',
      title: '关于明确长江保护有关条款适用范围和对化工项目认定标准进行解释的建议',
      author: '全团',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-115',
      title: '关于有效保护好野生动物不造成农民群众生产生活严重影响的建议',
      author: '郑望春',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-116',
      title: '关于支持全国革命老区重点城市巴中实施山水林田湖草一体化保护和修复项目的建议',
      author: '戴学斌',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-117',
      title: '关于将每年7月25日设立为古树名木保护日的建议',
      author: '刘素英',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-118',
      title: '关于支持达州建设多维空间复合林业经济示范带的建议',
      author: '胡晓玲',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-119',
      title: '关于加大生物多样性保护支持力度的建议',
      author: '江吉村',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-120',
      title: '关于支持若尔盖国家公园创建的建议',
      author: '罗振华',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-121',
      title: '关于完善林草碳汇项目开发机制的建议',
      author: '彭映梅',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-122',
      title: '关于支持四川贡嘎山山水林田湖草沙冰一体化保护和修复工程的建议',
      author: '余德春',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-123',
      title: '关于加快推动大科学装置成果转化发挥大科学装置原始策源作用的建议',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-124',
      title: '关于推动高质量人工智能发展，提升国际软实力的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-125',
      title: '关于新型举国科研体系推动生物医药卡脖子技术发展的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-126',
      title: '关于建设国家元宇宙创新应用先导区的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-127',
      title: '关于国家智能网联汽车“车路云一体化”应用试点的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-128',
      title: '关于国家数据基础设施区域性节点布局的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-129',
      title: '关于推动高质量人工智能发展，提升国际软实力的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-130',
      title: '关于利用数字技术为畜牧业节粮提效注入新质生产力的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-131',
      title: '关于树牢大食物观建好森林粮库的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-132',
      title: '关于推动“科技-农业-金融”良性循环助力乡村振兴和“农业强国”建设的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-133',
      title: '关于多措并举推动生猪行业高质量发展的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-134',
      title: '关于强化乡村人才培养激发乡村振兴活力的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-135',
      title: '“万企兴万村”行动暨托底性帮扶',
      author: '',
      link: '',
      topicKey: 'four',
    },
    {
      id: '24-four-136',
      title: '关于打造美丽中国先行区的提案',
      author: '',
      link: '',
      topicKey: 'four',
    },
    { id: '24-four-137', title: '新质生产力+生态环保', author: '', link: '', topicKey: 'four' },
    {
      id: '24-law-001',
      title: '关于最高人民法院加大力度推进裁判文书上网的建议',
      author: '庹庆明',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-002',
      title: '关于对刑法第215条司法解释的建议',
      author: '曾娜',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-003',
      title: '关于进一步深化执行管理体制改革，强化执行联动的建议',
      author: '李世亮',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-004',
      title: '关于进一步规范法律服务市场管理的建议',
      author: '李世亮',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-005',
      title: '关于加大对证券违法犯罪活动的刑事惩戒力度的建议',
      author: '李世亮',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-006',
      title: '关于加强涉外法治体系高质量建设的建议',
      author: '李世亮',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-007',
      title: '关于在死刑复核阶段向辩护律师提供电子卷宗的建议',
      author: '李世亮',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-008',
      title: '关于修改《刑法》第31条的建议',
      author: '李世亮',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-009',
      title: '关于构建全国统一且适合我国国情发展的预重整制度的建议',
      author: '李世亮',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-010',
      title: '关于政府采购法修订中有效规制恶意投诉行为破坏采购秩序的建议',
      author: '刘仓理',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-011',
      title: '关于将《残疾人教育条例》上升为《特殊教育法》的建议',
      author: '刘素英',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-012',
      title: '关于加强未成年人司法社会支持体系建设的建议',
      author: '罗春梅',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-013',
      title:
        '关于在法律中明确“检察机关在履行法律监督职责中发现行政机关违法行使职权或者不行使职权的，可以依照法律规定制发检察建议等督促其纠正”的建议',
      author: '罗春梅',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-014',
      title: '关于加强区县法检部门经费保障的建议',
      author: '乔进双梅',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-015',
      title: '关于做好相对薄弱法院脱薄工作的建议',
      author: '乔进双梅',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-016',
      title: '关于推进涉案企业合规立法的建议',
      author: '全团',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-017',
      title: '关于进一步规范枪支认定及管理的建议',
      author: '尚丽平',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-018',
      title: '关于完善“笑气”社会治理问题的建议',
      author: '李慧',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-019',
      title: '关于加快推进刑事“涉案财物诉讼”立法的建议',
      author: '王树江',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-020',
      title: '关于对银行业以房抵债有关法律适用予以重视并依法保护的建议',
      author: '魏琴',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-021',
      title: '构建高质量公共法律服务体系',
      author: '吴德',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-022',
      title: '关于深入推进涉案企业合规改革的建议',
      author: '杨心平',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-023',
      title: '关于进一步规范涉案企业合规适用的建议',
      author: '郑功成',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-024',
      title: '关于完善成年监护体系保障特殊群体权益的建议',
      author: '郑喆轩',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-025',
      title: '关于加大扶持民营企业科技创新的建议',
      author: '耿福能',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-026',
      title: '关于积极推动民营企业新时代高质量发展的建议',
      author: '戴学斌',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-027',
      title: '关于大力挖掘弘扬红色法治文化的提案',
      author: '',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-028',
      title: '关于规范法律咨询公司的提案',
      author: '',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-029',
      title: '关于适时修改《中小企业促进法》的提案',
      author: '',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-law-030',
      title:
        '关于适时修改中小企业促进法的提案；加快推进数据基础制度法律的立法进程，推动数字变革赋能社会发展',
      author: '',
      link: '',
      topicKey: 'law',
    },
    {
      id: '24-plan-001',
      title: '关于修订和继续执行移民后期扶持相关政策的建议',
      author: '郑望春',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-002',
      title: '关于给予全国革命老区重点城市巴中精准扶持电价政策的建议',
      author: '戴学斌',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-003',
      title: '关于支持四川省广元市创建国家物流枢纽承载城市的建议',
      author: '董里',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-004',
      title: '关于支持泸州建设“一带一路”及长江经济带战略支点城市的建议',
      author: '董伟',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-005',
      title: '关于支持泸州市创建国家创新型城市的建议',
      author: '董伟',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-006',
      title: '关于将沿江货运铁路重庆经泸州至宜宾段项目纳入国省规划的建议',
      author: '董伟',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-007',
      title: '关于给予高寒高海拔城镇供气供暖供氧政策支持的建议',
      author: '冯发贵',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-008',
      title: '关于加快电力通道建设的建议',
      author: '冯发贵',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-009',
      title: '关于将阿坝州第三机场纳入《全国民用运输机场布局规划》的建议',
      author: '格西王母',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-010',
      title: '关于恳请支持东出北上国际陆港枢纽的建议',
      author: '苟兴龙',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-011',
      title: '关于支持高铁建设用地保障等事项的建议',
      author: '苟兴龙',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-012',
      title: '关于支持四川打造国家战略产业备份基地更好建设国家战略腹地的建议',
      author: '黄河',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-013',
      title: '关于加快推进四川甘孜涉藏农牧区光伏独立供电农网延伸改造的建议',
      author: '江吉村',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-014',
      title: '关于大力支持建设“川滇藏”国家能源安全“大后方”的建议',
      author: '里赞',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-015',
      title: '关于稳定可再生能源补贴政策 维护政府公信力的建议',
      author: '刘汉元',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-016',
      title: '关于加强工业固废磷石膏无害化处理及综合应用的建议',
      author: '吕祖艳',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-017',
      title: '关于支持达州设立国内首个海相深部钾盐资源开发利用试验区的建议',
      author: '严卫东',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-018',
      title: '关于支持达州高新区创建国家高新区的建议',
      author: '吕祖艳',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-019',
      title: '关于推动新能源高质量发展，助力新型电力系统加快构建的建议',
      author: '蒙媛',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-020',
      title: '关于强化空调负荷优化管理助力电力安全可靠供应的建议',
      author: '蒙媛',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-021',
      title: '关于加快推动东西部协作产业转移的建议',
      author: '欧阳梅',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-022',
      title: '关于将真空技术产业列为国家战略产业的建议',
      author: '欧阳梅',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-023',
      title: '关于进一步支持川藏经济协作试验区加快建设的建议',
      author: '彭映梅',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-024',
      title: '关于加速推进社会信用建设立法规范信用信息管理的建议',
      author: '朱永繁',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-025',
      title: '关于加强国家战略腹地能源保障进一步提高四川省能源保供能力的建议',
      author: '全团建议',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-026',
      title: '关于拓展深化成都西部片区国家城乡融合发展试验区的建议',
      author: '全团',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-027',
      title: '关于加快长江上游—金沙江下游千公里航运体系建设的建议',
      author: '全团',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-028',
      title: '关于恳请国家发改委支持江安县古贤坝大桥',
      author: '任敏',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-029',
      title: '关于加强数字政府应用和场景建设加快构建以信用为依托的经济治理体系的建议',
      author: '施小琳',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-030',
      title: '关于支持四川省自贡市创建国家物流枢纽承载城市的建议',
      author: '四川团 李慧',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-031',
      title: '天然气产地就地高效转化利用',
      author: '曾洪扬',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-032',
      title:
        '关于支持在全国革命老区重点城市巴中探索建立天然气、石油等资源开发新模式和利益共享机制的建议',
      author: '汪其德',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-033',
      title: '关于推广公园城市规划建设模式的建议',
      author: '王麒',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-034',
      title: '关于进一步统筹推动长江经济带高质量发展的建议',
      author: '王麒',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-035',
      title: '关于进一步改造老旧厂区矿区的建议',
      author: '王晓梅',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-036',
      title: '关于支持阿坝州水网规划纳入国家水网规划的建议',
      author: '新甲旦真',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-037',
      title: '关于支持成都市进一步加大新时代战略大后方建设力度的建议',
      author: '许强',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-038',
      title: '关于做好移民后扶相关工作的建议',
      author: '晏鲁作',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-039',
      title: '关于加快推进边远农牧区光伏独立供电农网延伸改造的建议',
      author: '余德春',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-040',
      title: '关于持续加大对国家城乡融合发展试验区建设支持力度的建议',
      author: '余绍容',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-041',
      title: '关于支持宜宾—泸州联合申报国家综合货运枢纽补链强链城市的建议（联合建议）',
      author: '余先河',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-042',
      title: '关于制定出台支持攀枝花钒钛产业电价政策的建议',
      author: '邹明',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-043',
      title: '关于出台川陕革命老区协同推进高质量发展实施方案的建议',
      author: '高鹏凌',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-044',
      title: '关于打造优势产业树立特色品牌 实现共同富裕的建议',
      author: '耿福能',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-045',
      title: '关于加强川西南地区大中型水利水库建设解决用水时空不均问题的建议',
      author: '郑望春',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-046',
      title: '关于支持汉源县建设旭家沟水库的建议',
      author: '郑望春',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-047',
      title: '关于加快建立嘉陵江联合调度机制的建议',
      author: '董里',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-048',
      title: '关于加快完善基层水利设施建设的建议',
      author: '李君',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-049',
      title: '关于加大对大中型灌区末级渠系配套支持力度的建议',
      author: '王善平',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-050',
      title: '关于加快建设毗河供水二期工程的建议',
      author: '王善平',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-051',
      title: '关于加强农田水利设施建设管护的建议',
      author: '王晓梅',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-052',
      title: '关于巩固提升农村安全饮水工程的建议',
      author: '余德春',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-053',
      title: '关于支持乌蒙山区叙永县、古蔺县大型水利工程建设的建议',
      author: '余先河',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-054',
      title: '关于地震断裂带房屋避险搬迁的建议',
      author: '郑望春',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-055',
      title: '关于地质灾害避险搬迁补偿机制和补助标准的建议',
      author: '郑望春',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-056',
      title: '关于支持达州天然气锂钾资源开发利用的建议',
      author: '苟兴龙',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-057',
      title: '关于支持达州宣汉建设全国百万吨级钾肥基地的建议',
      author: '胡晓玲',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-058',
      title: '关于支持水面光伏项目发展，促进土地资源复合利用的建议',
      author: '刘汉元',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-059',
      title: '关于扩大农村集体经营性建设用地入市试点范围的建议',
      author: '汪其德',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-060',
      title: '关于返还阿坝州探矿权出让收入资金的建议',
      author: '王树明',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-061',
      title: '关于规范国内矿产粗铜新增产能，推动铜产业高质量发展的建议',
      author: '奚正平',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-062',
      title: '关于增加地质灾害避险搬迁补助标准的建议',
      author: '严卫东',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-063',
      title: '关于支持达州设立国内首个深部海相钾盐资源开发利用试验区的建议',
      author: '严卫东',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-plan-064',
      title: '关于鼓励建设钒钛磁铁矿非高炉冶炼示范线的建议',
      author: '邹明',
      link: '',
      topicKey: 'plan',
    },
    {
      id: '24-fin-001',
      title: '关于调整个人所得税税率与级数的建议',
      author: '庹庆明',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-002',
      title: '关于给予全国革命老区重点城市巴中差异化转移支付政策的建议',
      author: '戴学斌',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-003',
      title: '关于增加中央财政转移支付用于基层医疗机构医务人员全额拨款绩效管理的建议',
      author: '董伟',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-004',
      title: '关于优化个人所得税税制的建议',
      author: '董伟',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-005',
      title: '落实中小银行改革化险支持政策的建议',
      author: '黄毅',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-006',
      title:
        '关于取消《中华人民共和国增值税暂行条例》中划分“一般纳税人”和“小规模纳税人”纳税模式的建议',
      author: '李玉梅',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-007',
      title: '关于加快推进增值税税制绿色化改革的建议',
      author: '梁伟',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-008',
      title: '关于推动中央财政补贴覆盖渔业保险的建议',
      author: '刘汉元',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-009',
      title: '对赌协议个人股东业绩补偿金所得税问题建议',
      author: '刘素英',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-010',
      title: '关于增加地质灾害避险搬迁补助标准的建议',
      author: '严卫东',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-011',
      title: '关于废弃电器电子产品基金补贴资金尽快下拨的建议',
      author: '柳江',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-012',
      title: '关于将林竹机械纳入农机购置补贴的建议',
      author: '乔进双梅',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-013',
      title: '关于继续加大财政金融政策力度支持清理拖欠企业账款的建议',
      author: '唐安斌',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-014',
      title: '关于支持阿坝州创建大熊猫国家公园小水电站清退补偿资金的建议',
      author: '王树明',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-015',
      title: '关于进一步降低西部地区高新技术企业企业所得税税率的建议',
      author: '王瑛',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-016',
      title: '关于改进年终奖个税计算方法的建议',
      author: '张祖涛',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-017',
      title: '关于构建全国统一投资者适当性管理平台提升金融市场效率和监管效能的建议',
      author: '董伟',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-018',
      title: '关于充分运用REITs工具激发市场活力，有效支持西部地区高质量发展的建议',
      author: '黄毅',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-019',
      title: '关于加强对中小金融机构化险合法权益保护的建议',
      author: '黄毅',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-020',
      title: '关于加强金融开放监管体系建设的建议',
      author: '梁伟',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-021',
      title: '关于尽快制定出台《金融安全法》的建议',
      author: '梁伟',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-022',
      title: '关于进一步完善西部欠发达地区科技创新和成果转化金融服务体系的建议',
      author: '刘政',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-023',
      title: '关于高度重视并做好存量PPP项目处置工作的建议',
      author: '朱永繁',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-024',
      title: '关于严厉打击分布式小金额网络诈骗的建议',
      author: '尚丽平',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-025',
      title: '关于推进重大自然灾害专门保险立法的建议',
      author: '王树江',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-026',
      title: '关于规范供应链金融发展的建议',
      author: '严宝玉',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-027',
      title: '关于增加地方政府一般债券发行规模的建议',
      author: '杨心平',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-028',
      title: '关于加快建立住宅保险制度的建议',
      author: '郑功成',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-029',
      title: '关于将犬只伤人的刑事责任写入刑法修正案的建议',
      author: '庹庆明',
      link: '',
      topicKey: 'finance',
    },
    {
      id: '24-fin-030',
      title: '关于尽快制定《预防性环境民事公益诉讼规范》的建议',
      author: '庹庆明',
      link: '',
      topicKey: 'finance',
    },
  ],
  2023: [
    {
      id: '23-tra-001',
      title: '关于支持尽快启动重庆至自贡至雅安铁路建设的建议',
      author: '曾道群',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-002',
      title: '关于支持尽快启动雅安至甘洛铁路建设的建议',
      author: '郑望春',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-003',
      title: '关于出台《川陕革命老区综合交通基础设施振兴发展规划》的建议',
      author: '高鹏凌',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-004',
      title: '关于加快西部陆海新通道西线铁路通道建设的建议',
      author: '四川全团建议',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-005',
      title: '关于将陕西宝鸡—汉中—四川巴中铁路作为区域高速铁路纳入相关规划并加快建设的建议',
      author: '汪其德',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-006',
      title: '关于加快推进民族地区交通基础设施建设的建议',
      author: '余德春',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-007',
      title: '关于将广安至重庆快速通道纳入交通运输部《公路“十四五”发展规划中期调整方案》的建议',
      author: '赵波',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-008',
      title: '关于支持将重庆渝北至四川广安铁路纳入国家铁路专项规划的建议',
      author: '赵波',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-009',
      title: '关于修建“雅安到西宁”铁路的建议',
      author: '',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-010',
      title: '关于加快新成昆高铁规划建设的建议',
      author: '乔进双梅',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-011',
      title: '关于加快G0611张掖至汶川高速公路（四川段）建设的建议',
      author: '王树明',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-012',
      title: '关于将阿坝第三机场纳入《全国民用运输机场布局规划》并尽早开工建设的建议',
      author: '王树明',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-013',
      title: '关于优化中老铁路运行配套政策 加速西部地区融入“一带一路”建设的建议',
      author: '邹明',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-014',
      title: '关于优化中老铁路配套举措加速“一带一路”建设的提案',
      author: '',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-015',
      title: '关于加快西部陆海新通道西线铁路建设的提案',
      author: '',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-016',
      title: '关于在川陕革命老区规划建设成巴安高速铁路的提案',
      author: '',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-017',
      title: '关于推动收费公路高质量发展的提案',
      author: '',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-018',
      title: '关于支持甘孜州骨干高速路网建设的建议',
      author: '',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-tra-019',
      title: '关于建设川渝东北一体化水资源配置工程的提案',
      author: '',
      link: '',
      topicKey: 'traffic',
    },
    {
      id: '23-cy-001',
      title: '关于支持尽快启动重庆至自贡至雅安铁路建设的建议',
      author: '曾道群',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-002',
      title: '关于支持尽快启动雅安至甘洛铁路建设的建议',
      author: '郑望春',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-003',
      title: '关于优化重大生产力布局促进成渝地区双城经济圈建设的建议',
      author: '四川全团建议',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-004',
      title: '关于健全国家层面推动成渝地区双城经济圈建设工作推进机制的建议',
      author: '四川全团建议',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-005',
      title: '关于设立成渝地区双城经济圈国家文化和旅游创新改革试验区的建议',
      author: '何延政',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-006',
      title: '关于支持成渝地区双城经济圈海关特殊监管场所建设的建议',
      author: '刘延安',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-007',
      title: '关于鼓励支持海外留学归国人员和侨资企业参与成渝双城经济圈建设的建议',
      author: '王麟',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-008',
      title: '关于加快川渝执法司法一体化进程的建议',
      author: '王瑛',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-009',
      title: '关于打造川渝地区天然气与新能源绿色融合发展新模式的建议',
      author: '文绍牧',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-010',
      title: '关于建立成渝地区双城经济圈建设高规格工作机制的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-011',
      title: '关于进一步完善成渝地区双城经济圈对外通道的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-012',
      title: '关于成渝地区双城经济圈部分县化解隐性债务的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-013',
      title: '关于建立成渝地区双城经济圈建设高规格工作机制的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-014',
      title: '关于进一步完善成渝地区双城经济圈对外通道的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-015',
      title: '关于成渝地区双城经济圈部分县化解隐性债务的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-016',
      title: '关于布局综合性国家科学中心的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-017',
      title: '关于加快西部科学城建设的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-018',
      title: '关于建立成渝地区双城经济圈建设高规格工作机制的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-019',
      title: '关于进一步完善成渝地区双城经济圈对外通道的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-020',
      title: '关于进一步完善成渝地区双城经济圈对外通道的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-021',
      title: '关于建设川渝东北一体化水资源配置工程的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-022',
      title: '关于成渝地区双城经济圈部分县化解隐性债务的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-023',
      title: '关于建立成渝地区双城经济圈建设高规格工作机制的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-024',
      title: '关于进一步完善成渝地区双城经济圈对外通道的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-025',
      title: '关于成渝地区双城经济圈部分县化解隐性债务的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-cy-026',
      title: '关于川渝地区天然气资源就地高效转化利用的提案',
      author: '',
      link: '',
      topicKey: 'chengyu',
    },
    {
      id: '23-ref-001',
      title: '关于打通中小银行改革化险“堵点”，提升支持实体经济能力的建议',
      author: '黄毅',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-ref-002',
      title: '关于利用REITs优化基础设施建设和扩充市场投融资渠道的建议',
      author: '黄毅',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-ref-003',
      title: '关于提振民营经济信心与活力，推进实体经济高质量发展的建议',
      author: '黄毅',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-ref-004',
      title: '关于支持丝纺行业持续健康发展的建议',
      author: '王丽',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-ref-005',
      title: '关于深化公平竞争，提升民营经济信心的建议',
      author: '戴学斌',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-ref-006',
      title: '关于改进小微企业信贷服务进一步优化营商环境的建议',
      author: '刘延安',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-ref-007',
      title: '关于高度重视解决大型企业拖欠专精特新中小企业账款问题 增强国家科技创新竞争力的再建议',
      author: '刘延安',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-ref-008',
      title: '关于促进汽车消费，提振经济回升的建议',
      author: '王麟',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-ref-009',
      title: '关于精准施策，推进民营经济高质量发展的建议',
      author: '王麟',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-ref-010',
      title: '关于增强民营企业发展信心的建议的提案',
      author: '',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-ref-011',
      title: '关于进一步提升民营企业发展信心的提案',
      author: '',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-ref-012',
      title: '关于支持四川打造参与国际竞争新基地的提案',
      author: '',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-ref-013',
      title: '关于促进互联网货运平台企业规范健康发展的提案',
      author: '',
      link: '',
      topicKey: 'reform',
    },
    {
      id: '23-gr-001',
      title: '关于优化进口饲用粮配额分配机制的建议',
      author: '刘汉元',
      link: '',
      topicKey: 'grain',
    },
    {
      id: '23-gr-002',
      title: '关于建设新时代更高水平“天府粮仓”的建议',
      author: '黄河',
      link: '',
      topicKey: 'grain',
    },
    {
      id: '23-gr-003',
      title: '关于加快建设川渝地区大豆良种繁育基地更好维护国家粮食安全的建议',
      author: '欧阳梅',
      link: '',
      topicKey: 'grain',
    },
    {
      id: '23-gr-004',
      title: '关于支持四川建设新时代更高水平“天府粮仓”和擦亮农业大省“金字招牌”的建议',
      author: '四川全团建议',
      link: '',
      topicKey: 'grain',
    },
    {
      id: '23-gr-005',
      title: '关于持续加大高标准农田建设投入力度的建议',
      author: '四川全团建议',
      link: '',
      topicKey: 'grain',
    },
    {
      id: '23-gr-006',
      title: '关于优化种业发展支持政策的建议',
      author: '李云',
      link: '',
      topicKey: 'grain',
    },
    {
      id: '23-gr-007',
      title: '关于加大农业投入的建议',
      author: '',
      link: '',
      topicKey: 'grain',
    },
    {
      id: '23-gr-008',
      title: '关于支持雅安全域现代农业绿色发展的建议',
      author: '',
      link: '',
      topicKey: 'grain',
    },
    {
      id: '23-gr-009',
      title: '关于高效实施好高标准农田建设工程的建议',
      author: '曾道群',
      link: '',
      topicKey: 'grain',
    },
    {
      id: '23-gr-010',
      title: '关于加快完善丘陵地区农田灌溉“最后一公里”的建议',
      author: '李玉梅',
      link: '',
      topicKey: 'grain',
    },
    {
      id: '23-gr-011',
      title: '关于打造新时代更高水平“天府粮仓”的提案',
      author: '',
      link: '',
      topicKey: 'grain',
    },
  ],
}
export const topicDetailByYear = {
  2025: [
    {
      id: '25-1',
      content: '47件民生建议是四川增进民生福祉、回应群众期盼的温度',
      tag: '民生',
      topicKey: 'livelihood',
    },
    {
      id: '25-2',
      content: '8件生态保护建议是四川加快绿色转型、筑牢生态屏障的进度',
      tag: '生态保护',
      topicKey: 'ecology',
    },
    {
      id: '25-3',
      content: '8件文化旅游建议是四川彰显文化魅力、传播四川声音的热度',
      tag: '文化旅游',
      topicKey: 'culture',
    },
    {
      id: '25-4',
      content: '2件新质生产力建议是四川塑造发展新动能、构建现代化产业体系的精度',
      tag: '新质生产力',
      topicKey: 'industry',
    },
  ],
  2024: [
    {
      id: '24-1',
      content: '138件“四个发力”建议是四川把握战略定位、推动全面发展的力度',
      tag: '四个发力',
      topicKey: 'four',
    },
    {
      id: '24-2',
      content: '30件法治四川建议是四川推进依法治理、规范社会运行的法度',
      tag: '法治四川',
      topicKey: 'law',
    },
    {
      id: '24-3',
      content: '64件发展规划建议是四川谋划长远发展、锚定未来方向的高度',
      tag: '发展规划',
      topicKey: 'plan',
    },
    {
      id: '24-4',
      content: '28件财税金融建议是四川强化要素保障、夯实发展根基的强度',
      tag: '财政金融',
      topicKey: 'finance',
    },
  ],
  2023: [
    {
      id: '23-1',
      content: '19件交通建议是四川加速内联外畅、建设现代化综合交通体系的广度',
      tag: '交通',
      topicKey: 'traffic',
    },
    {
      id: '23-2',
      content: '28件成渝地区双城经济圈建议是四川深化川渝协同、唱好“双城记”的跨度',
      tag: '成渝地区双城经济圈',
      topicKey: 'chengyu',
    },
    {
      id: '23-3',
      content: '15件改革开放建议是四川破除发展壁垒、提升开放能级的态度',
      tag: '改革开放',
      topicKey: 'reform',
    },
    {
      id: '23-4',
      content: '11件天府粮仓建议是四川保障粮食安全、夯实农业根基的尺度',
      tag: '天府粮仓',
      topicKey: 'grain',
    },
  ],
}
