export const topicYearTabs = ['2025', '2024', '2023']
export const topicSphereList = [
  { key: 'integration', label: '城乡融合', size: 'md' },
  { key: 'plan', label: '发展规划', size: 'md' },
  { key: 'four', label: '四个发力', size: 'xl' },
  { key: 'law', label: '法制四川', size: 'md' },
  { key: 'traffic', label: '交通', size: 'lg' },
  { key: 'livelihood', label: '民生', size: 'sm' },
  { key: 'finance', label: '财税金融', size: 'lg' },
  { key: 'chengyu', label: '成渝地区双城经济圈', size: 'wide' },
  { key: 'industry', label: '产业', size: 'sm' },
  { key: 'reform', label: '改革开放', size: 'lg' },
  { key: 'other', label: '其他', size: 'sm' },
  { key: 'culture', label: '宣传文旅', size: 'xl' },
  { key: 'ecology', label: '生态', size: 'lg' },
  { key: 'grain', label: '天府粮仓', size: 'sm' },
]
export const topicListByYear = {
  2025: [
    {
      id: '25-1',
      title: '关于推动川渝以大科学装置为抓手联合打造国家科技战略腹地的建议',
      date: '2025年3月12日',
      source: '人民日报',
      author: '王麒',
      link: '',
    },
    {
      id: '25-2',
      title: '关于加快建设嘉陵江井口生态航运枢纽突破嘉陵江黄金水道瓶颈制约的建议',
      date: '2025年3月12日',
      source: '人民日报',
      author: '王瑛',
      link: '',
    },
    {
      id: '25-3',
      title: '关于支持四川建设成为全国氢能产业发展高地的建议',
      date: '2025年3月12日',
      source: '人民日报',
      author: '欧阳梅',
      link: '',
    },
    {
      id: '25-4',
      title: '关于推动川渝以大科学装置为抓手联合打造国家科技战略腹地的建议',
      date: '2025年3月12日',
      source: '人民日报',
      author: '王璞',
      link: '',
    },
    {
      id: '25-5',
      title: '关于加快建设嘉陵江井口生态航运枢纽突破嘉陵江黄金水道瓶颈制约的建议',
      date: '2025年3月12日',
      source: '人民日报',
      author: '欧阳梅',
      link: '',
    },
  ],
  2024: [
    {
      id: '24-1',
      title: '关于优化川渝两地产业链协同机制提升科技成果转化效率的建议',
      date: '2024年3月11日',
      source: '人民日报',
      author: '代表团',
      link: '',
    },
    {
      id: '24-2',
      title: '关于加快县域医疗服务能力提升推动基层医疗资源均衡配置的建议',
      date: '2024年3月11日',
      source: '人民日报',
      author: '代表团',
      link: '',
    },
    {
      id: '24-3',
      title: '关于完善绿色低碳产业扶持政策推动重点园区节能改造的建议',
      date: '2024年3月11日',
      source: '人民日报',
      author: '代表团',
      link: '',
    },
  ],
  2023: [
    {
      id: '23-1',
      title: '关于推进数字政府建设提升公共服务一网通办质量的建议',
      date: '2023年3月10日',
      source: '人民日报',
      author: '代表团',
      link: '',
    },
    {
      id: '23-2',
      title: '关于加强重要农产品仓储物流体系建设保障粮食安全的建议',
      date: '2023年3月10日',
      source: '人民日报',
      author: '代表团',
      link: '',
    },
    {
      id: '23-3',
      title: '关于打造区域文旅品牌推进文化消费场景创新的建议',
      date: '2023年3月10日',
      source: '人民日报',
      author: '代表团',
      link: '',
    },
  ],
}
export const topicDetailByYear = {
  2025: [
    {
      id: '25-1',
      content: '关于推动川渝以大科学装置为抓手联合打造国家科技战略腹地的建议',
      tag: '科技创新',
      author: '—— 王麒',
    },
    {
      id: '25-2',
      content: '关于加快建设嘉陵江井口生态航运枢纽突破嘉陵江黄金水道瓶颈制约的建议',
      tag: '交通 / 航运',
      author: '—— 王瑛',
    },
    {
      id: '25-3',
      content: '关于支持四川建设成为全国氢能产业发展高地的建议',
      tag: '产业 / 氢能',
      author: '—— 欧阳梅',
    },
    {
      id: '25-4',
      content: '关于推动川渝以大科学装置为抓手联合打造国家科技战略腹地的建议',
      tag: '科技创新',
      author: '—— 王璞',
    },
    {
      id: '25-5',
      content: '关于加快建设嘉陵江井口生态航运枢纽突破嘉陵江黄金水道瓶颈制约的建议',
      tag: '交通 / 航运',
      author: '—— 欧阳梅',
    },
  ],
  2024: [
    {
      id: '24-1',
      content: '关于优化川渝两地产业链协同机制提升科技成果转化效率的建议',
      tag: '成渝地区双城经济圈',
      author: '—— 代表团',
    },
    {
      id: '24-2',
      content: '关于加快县域医疗服务能力提升推动基层医疗资源均衡配置的建议',
      tag: '民生',
      author: '—— 代表团',
    },
    {
      id: '24-3',
      content: '关于完善绿色低碳产业扶持政策推动重点园区节能改造的建议',
      tag: '生态 / 产业',
      author: '—— 代表团',
    },
  ],
  2023: [
    {
      id: '23-1',
      content: '关于推进数字政府建设提升公共服务一网通办质量的建议',
      tag: '改革开放',
      author: '—— 代表团',
    },
    {
      id: '23-2',
      content: '关于加强重要农产品仓储物流体系建设保障粮食安全的建议',
      tag: '天府粮仓',
      author: '—— 代表团',
    },
    {
      id: '23-3',
      content: '关于打造区域文旅品牌推进文化消费场景创新的建议',
      tag: '宣传、文旅',
      author: '—— 代表团',
    },
  ],
}
export const topicProfileByAuthor = {
  王麒: {
    name: '王麒',
    subtitle: '（成都）',
    titles: [
      '农工党四川省委会副主委',
      '成都市委会主委',
      '成都市政协副主席',
      '四川大学华西医院炎症性肠病中心主任',
    ],
  },
  王瑛: {
    name: '王瑛',
    subtitle: '（成都）',
    titles: ['四川省政协委员', '交通运输领域专家', '长期关注嘉陵江航运建设'],
  },
  欧阳梅: {
    name: '欧阳梅',
    subtitle: '（成都）',
    titles: [
      '省人大代表',
      '能源产业研究专家',
      '长期关注氢能产业发展',
      '长期关注氢能产业发展',
      '长期关注氢能产业发展',
      '长期关注氢能产业发展',
    ],
  },
  王璞: {
    name: '王璞',
    subtitle: '（成都）',
    titles: ['省人大代表', '科技创新领域从业者', '关注区域协同创新发展'],
  },
  代表团: {
    name: '代表团',
    subtitle: '（四川）',
    titles: ['四川代表团', '聚焦区域发展与民生议题'],
  },
}
